### ISSUE TITLE
Hooking up to Redis?

### ISSUE THREAD

**Issue by MarkMurphy** [kickstarter/rack-attack#102]
Would be nice to see an example in the REDME of how this can be configured to connect to Redis. Can someone provide me with a link which explains how to do that?

**Comment by Chrisgo-75** [comment]
Thank you @fluxsaas. You helped me with figuring out how to configure Rack::Attack to use Redis as its caching mechanism.

```ruby
# File: rack_attack.rb
class Rack::Attack
	Rack::Attack.cache.store = ActiveSupport::Cache::RedisStore.new("redis://example.com:6666/0/cache", { expires_in: 480.minutes })
	... ...
end
```

**Comment by waruboy** [comment]
@fluxsaas exactly what I need. Redis connection to RedisToGo on heroku app. Thanks!

**Comment by saygun** [comment]
Those who faced same problem in Rails 5 might check 
```
config/development.rb

config.cache_store = :redis_store # comment out this one
````

**Comment by Skillvendor** [comment]
@saygun You have no idea how much i love you

**Comment by lordplagus02** [comment]
Is there a 2020 method for this or have the solutions remained the same?

**Comment by grzuy** [comment]
Hi @lordplagus02,

Since `v5.4.0` (https://github.com/kickstarter/rack-attack/blob/master/CHANGELOG.md#540---2018-07-02) you can connect rack-attack directly to redis by setting the store to the `Redis` client:

```ruby
Rack::Attack.cache.store = Redis.new(...) 
```

**Comment by Aryk** [comment]
Does this library automatically set expirations on the redis objects. LIke for example, if we have a "period" of 5.minutes on some throttling. After 5 minutes that key is gone right? Or is there no purging mechanism?
