### ISSUE TITLE
Implement exponential backoff

### ISSUE THREAD

**Issue by reedloden** [kickstarter/rack-attack#106]
It would be really awesome if Rack::Attack supported exponential backoff so as people continue to misbehave, their ban times increase (maybe up to some max time).

This article has some useful thoughts and tables about it:
https://devcentral.f5.com/articles/implementing-the-exponential-backoff-algorithm-to-thwart-dictionary-attacks

**Comment by zmillman** [comment]
https://github.com/kickstarter/rack-attack/wiki/Advanced-Configuration :smile:

**Comment by zmillman** [comment]
@reedloden - does the Advanced Configuration page solve your issue?

**Comment by reedloden** [comment]
I haven't had time to test. I could close this out if it's a problem... I hope to pick this up later this month.

**Comment by zmillman** [comment]
Haha, not a problem at all. Just wanted to check in since it had been a while :smiley:

**Comment by ktheory** [comment]
Closing this since it's covered in the advanced config docs.

Happy throttling! :sunflower:

**Comment by ACPK** [comment]
@reedloden - Was this ever tested?

**Comment by reedloden** [comment]
@ACPK Not sure if we ever implemented it in this fashion. I will check and see.

**Comment by ACPK** [comment]
@reedloden Thanks!

**Comment by em4nue1** [comment]
Can anyone confirm this approach actually works? To me, it seems like only the last rule is active.

In my example below, I only have a limit after the 10th request (`level = 5`). It should already limit after the 2nd request within 8 seconds etc.

```
(1..5).each do |level|
  throttle('req/ip', limit: (2 * level), period: (8 ** level).seconds) do |req|
    req.ip
  end
end
```

**Comment by reedloden** [comment]
@em4nue1 You need to have unique names for each throttle. So, use `throttle("req/ip/#{level}")` or similar.
