### ISSUE TITLE
RackAttack on Heroku and Fallback for Cache Stores 

### ISSUE THREAD

**Issue by pisaacs** [kickstarter/rack-attack#109]
Given Heroku's ephemeral file and process system, and the likely need to have more than 1 dyno/process for any serious production app, I assume it is neither optimal to use `:memory_store` nor `:file_store` for `config.cache_store` (since data points are split across siloed processes/file systems). 

According to the RackAttack guide, presumably apps employing throttling use either memcached or redis. I'm not too familiar with caching services, but if my memcached service fails, will rails/rack-attack fallback to the default rails cache store, file store? Or will the app throw errors and become unusable until the memcache service is back online?

I know I can pursue high availability memcached setup, but that costs a premium (based on my needs).

I would love to hear community members thoughts on this.

**Comment by pisaacs** [comment]
Very timely response! That might tip the scale toward redis for me. Earlier I was researching performance differences (http://bit.ly/1BCgFel) but it's good to know there's Multi AZ support for redis!! Thanks again for sharing.

**Comment by ktheory** [comment]
:+1: to using memcache as your production cache store.

> if my memcached service fails, will rails/rack-attack fallback to the default rails cache store, file store? Or will the app throw errors and become unusable until the memcache service is back online?

Just want to clarify a few things:

If you use memcache as your Rails.cache (i.e. [`config.cache_store = :dalli_store`](https://github.com/mperham/dalli#usage-with-rails-3x-and-4x)), then Rack::Attack will also use memcache as the cache store. There's no other cache store to fall back to.

By default, dalli has a [0.5 second timeout](https://github.com/mperham/dalli/blob/533792caf97e909332e72263afcca0f2ffec8577/lib/dalli/server.rb#L16). So if memcache is unavailable, dalli will quickly detect that and treat every request as a cache miss.

For rack-attack, that means that every throttle check has a count of 0, effectively allowing all requests.

So if you have a throttle that allows 1 req/s per IP address, and a client made 2 requests in a second, and memcache is unavailable, then both requests would be allowed.

**Comment by pisaacs** [comment]
Thank you @ktheory for your valuable insight!
