### ISSUE TITLE
Current cache key generation may not be always correct

### ISSUE THREAD

**Issue by vipulnsward** [kickstarter/rack-attack#11]
The method `Cache#count` at https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack/cache.rb#L26-L31

uses `Time.now.to_i` for key formation, along with expiry time.

Along with change over a Time.now, this would affect the key fetching. So throttling currently works only for a minute. And if near to end of minute, only upto the available seconds left.

I agree time based key makes sense, to not block all request from an ip, but the above scenario, bypasses throttling for now.

I was not sure, how to handle this, so filing an issue to discuss, so I could work over a fix.

**Comment by SirRawlins** [comment]
Although this is a very old issue, I think it may relate to the one I've just opened, where cache keys, particularly for longer periods of time are inconsistent.

https://github.com/kickstarter/rack-attack/issues/230
