### ISSUE TITLE
Blacklisting by Heroku parameter variables

### ISSUE THREAD

**Issue by michaelmittermayr** [kickstarter/rack-attack#110]
Hi guys,

Any way supporting blacklisting by using Heroku variables? It would simplify adding new domains to  Rack Attack config class. At the moment every time I need to blacklist a new domain I have to change code, commit and deploy eventually.

My Rack Attack config is:

```ruby
class Rack::Attack
  spammers = [ENV['HEROKU_VARIABLE']]
  blacklist("block referer spam") do |request|
    spammers.find { |spammer| request.referer =~ spammer } if spammers.present?
  end
end
```
HEROKU_VARIABLE is set on heroku to: \domain1\, \domain2\

However, for some reason this not working. 

This error is returned:
TypeError (type mismatch: String given):
2015-01-16T22:19:04.162106+00:00 app[web.1]:   config/initializers/rack-attack.rb:6:in `=~'

Thanks

**Comment by ktheory** [comment]
@michaelmittermayr It's totally possible, and you're solution is close. The error is that `=~` expects a Regexp, and you're giving it a string.

Check out the [`Regexp.union` method](http://www.ruby-doc.org/core-2.2.0/Regexp.html#method-c-union) to make a regexp that matches any of a bunch of strings.

Completely untested example code:
```ruby
class Rack::Attack
  # Split on a comma with 0 or more spaces after it.
  # E.g. ENV['HEROKU_VARIABLE'] = "foo.com, bar.com"
  # spammers = ["foo.com", "bar.com"]
  spammers = ENV['HEROKU_VARIABLE'].split(/,\s*/)

  # Turn spammers array into a regexp
  spammer_regexp = Regexp.union(spammers) # /foo\.com|bar\.com/
  blacklist("block referer spam") do |request|
    request.referer =~ spammer_regexp
  end
end
```

**Comment by michaelmittermayr** [comment]
@ktheory Seems to work :-) Cheers!
