### ISSUE TITLE
using filters seems to bypass whitelists?

### ISSUE THREAD

**Issue by nathwill** [kickstarter/rack-attack#112]
we're using something like:

```ruby
# Load Balancer & Firewall IPs. Never throttled or blocked.
our_ips = [
  '10.241.34', '23.45.67.89'
]

# Pass requests from ourselves
Rack::Attack.whitelist('our_selves') do |req|
  our_ips.any? { |i| req.ip.match /^#{i}/ }
end

# Ban hard for excessive traffic to single URL
Rack::Attack.blacklist('path_abuse') do |req|
  Rack::Attack::Allow2Ban.filter("#{req.ip}#{req.path}", maxretry: 150, findtime: 3.minutes, bantime: 30.minutes) do
    req.ip
  end
end
```

and the path_abuse blacklist seems to still apply to requests from '10.241.34.13' (our load balancer doing health checks) despite being caught by the 'our_selves' whitelist. is this intended behavior?

**Comment by zmillman** [comment]
Hmm, the README seems to saythat the whitelist should override any blacklists: https://github.com/kickstarter/rack-attack#how-it-works

Might also be possible that you have a bug in your whitelist code. I have no idea what the regex is doing :confounded: 

I think this might be a clearer implementation:

```ruby
# Pass requests from ourselves
Rack::Attack.whitelist('our_selves') do |req|
  our_ips.include?(req.ip)
end
```

**Comment by nathwill** [comment]
yeah, that's how we'd initially written it, but the regex is basically our cheap way of using string-matching to do subnet specification instead of requiring ipaddress, and using full CIDR-notated matching.

i initially thought the regex might've been incorrect as well, but that doesn't seem to be the case:

```
[nathwill@wyrd ~]$ irb
irb(main):001:0> our_ips = [
irb(main):002:1*   '10.241.34', '23.45.67.89'
irb(main):003:1> ]
irb(main):004:0> our_ips.any? { |i| '10.241.34.13'.match /^#{i}/ }
=> true
```

The README does seem to indicate that whitelisting should bypass, i didn't see it mentioned in correlation with the nested fail2ban/allow2ban use, which is why I was looking for clarification, what with the observed behavior seems to differ from what was implied. ;)

in any case, since it sounds like it *is* supposed to bypass, i'll keep looking and see if I can find some explanation. thanks for the help thus far!

**Comment by zmillman** [comment]
The whole Fail2Ban/Allow2Ban feature is complex and convoluted.

It's based on an 11-year old Unix script and the naming / API design is inconsistent with the rest of Rack::Attack. If a new major version of Rack::Attack were released, it's a pretty good candidate for being deprecated.

If you can find a way to use `Rack::Attack.throttle` instead, I'd recommend it :smiley: 

P.S. Ruby has a built-in helper method for what you're trying to do:
```ruby
Rack::Attack.whitelist('our_selves') do |req|
  our_ips.any? { |our_ip| req.ip.start_with?(our_ip) }
end
```

**Comment by nathwill** [comment]
ack. thanks for the tips!
