### ISSUE TITLE
Limits and forked servers

### ISSUE THREAD

**Issue by juniorjp** [kickstarter/rack-attack#114]
Hi,

When I use a block like this:

```
throttle('logins/ip', :limit => 5, :period => 20.seconds) do |req|
    if req.path == '/user/session' && req.post?
      req.ip
    end
  end
```

and I use a forked server like Unicorn. Will the limit be applied per worker or is it global? Since different requests with the same IP can go to different workers, I'd like to know this.

Thanks.

**Comment by zmillman** [comment]
Rack::Attack uses a separate cache store for keeping track of how many times a throttle has incremented towards the limit. Unless you're using ActiveSupport::Cache::MemoryStore (and if you are, you shouldn't be), you won't have any issues with throttles in a multi-worker configuration.

**Comment by juniorjp** [comment]
Thanks for the fast reply!

I am using dalli gem(a client for memcache), does it work fine with Rack::Attack?

**Comment by zmillman** [comment]
Yep, you should be good to go.

**Comment by ktheory** [comment]
Yup, @zmillman is right on.
