### ISSUE TITLE
Whitelist as last rule

### ISSUE THREAD

**Issue by antlegrand** [kickstarter/rack-attack#115]
Hi, 
Currently the whitelist is the first rule checked, but in some cases, the whitelist can be dynamic and requires a lookup.  In fact, I'm storing whitelisted ip/users in memcached since it can't be predetermined in advance.

I would like to check if the user is whitelisted only if the request going to be rejected (throttle), so in normal situations it won't hit the cache at all.

**Comment by zmillman** [comment]
Hmm, the check order is a pretty core part of the library right now and switching it around would probably create a lot of issues.

For your use case, I'd recommend a workaround of monkey-patching Rack::Attack#call: https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack.rb#L93

```ruby
class Rack::Attack
  # Monkey-patch to only check whitelist if a request is throttled
  def call(env)
    req = Rack::Attack::Request.new(env)

    if blacklisted?(req)
      self.class.blacklisted_response.call(env)
    elsif throttled?(req) && !whitelisted?(req)
      self.class.throttled_response.call(env)
    else
      tracked?(req)
      @app.call(env)
    end
  end
end
```

**Comment by ktheory** [comment]
> the check order is a pretty core part of the library right now and switching it around would probably create a lot of issues. Most importantly, users expect whitelists to supersede blacklists.

Yup.

@antlegrand Maybe add a check for your whitelist to each of your throttles? E.g.:

```
throttle('ip', limit: 10, period: 10) {
  req.ip unless Rails.cache.get('whitelisted_ips').include?(req.ip)
}
```
