### ISSUE TITLE
Throttling by number of concurrent connections

### ISSUE THREAD

**Issue by dmitry** [kickstarter/rack-attack#116]
Does anyone want to have the ability to limit number of concurrent connections by IP, user or api key? Actually there are no reason to limit number of parallel connections through rack, it can be done with nginx module or with the similar software on low level of abstraction. But sometimes you need more control over that feature:

- limit by any param, not just IP;
- log access (redis in this case);
- more settings available.

Let me know if anyone is interested in this feature, I will prepare the PR with this feature for this gem.

**Comment by ktheory** [comment]
:wave: Hi @dmitry,

Limiting concurrent connections is useful: I use it in nginx!

But I don't think it makes sense for rack-attack. Rack-attack is all about the `request`, and doesn't care about the response.

Tracking concurrent connections would require changing state as a request is sent, so I see it as outside of rack-attack's scope.

It'd be great to see this as a separate rubygem though.
