### ISSUE TITLE
One minute throttle does not throttle for one minute.

### ISSUE THREAD

**Issue by axelabs** [kickstarter/rack-attack#121]
I have the following throttle defined:
```
throttle('login/minute', limit: 5, period: 1.minute) do |request|
```
The throttle works, but clears whenever the clock changes to the next minute as opposed to throttling for 60 seconds.  Did I set it wrong?

**Comment by ktheory** [comment]
@axelabs thanks for using rack-attack.

It's working as intended. Changing the cache key on the minute (as opposed to when the first request started) simplifies rack-attack's implementation and is fewer memcached requests.

This means that a client may be able to make 2x the `limit` number of requests in one `period`; but over 2 or more periods, the limit is enforced accurately.
