### ISSUE TITLE
POST get through

### ISSUE THREAD

**Issue by dancinglightning** [kickstarter/rack-attack#127]
Hi,  (great tool btw)

with latest gem on rails 4.1 i have following filter

Rack::Attack.blacklist('block admin probes') do |req|
  # Request are blocked if the return value is truthy
  ["php" , "jsp" , "cgi", "asp", "cfm," "proxy.txt", "soapCaller", "Win32" , "HNAP1" , "w00tw00t",
    "pma" , "mysql" ,"msd" , "MySQL" , "jmx-console" , "ervlet" , "xml" , "cart" ,"install"].each do |no|
    return true if  req.path.include?(no)
  end

But still get POST requests coming though, like this (lograge format)

I, [2015-05-02T12:49:42.793418 #13089]  INFO -- : method=POST path=/cgi-bin/php-cgi.bin format= controller=page action=error_404 status=500 error='ActionController::InvalidAuthentic
ityToken:ActionController::InvalidAuthenticityToken' duration=0.77 view=0.00 db=0.00
F, [2015-05-02T12:49:42.795988 #13089] FATAL -- :
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.1.10/lib/action_controller/metal/request_forgery_protection.rb:176:in `handle_unverified_request'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.1.10/lib/action_controller/metal/request_forgery_protection.rb:202:in `handle_unverified_request'
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.1.10/lib/action_controller/metal/request_forgery_protection.rb:197:in `verify_authenticity_token'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:161:in `call
....

**Comment by tiegz** [comment]
@dancinglightning I'm not sure about the `POST` discrepancy, but that `each` loop is going to always return a truthy value. I would try this instead (and maybe a regexp beyond this):

``` ruby
["php" , "jsp" , "cgi", "asp", "cfm," "proxy.txt", "soapCaller", "Win32" , "HNAP1" , "w00tw00t",
"pma" , "mysql" ,"msd" , "MySQL" , "jmx-console" , "ervlet" , "xml" , "cart" ,"install"].any? do |no|
  req.path.include?(no)
end
```

**Comment by dancinglightning** [comment]
Sorry,  after the loop is
  return false
end

So luckily it does not always return true as that would mean all requests get blocked, or not.
And yes, a regexp would probably be faster. 
Still, there seems to be a misunderstanding or bug.

**Comment by michaeldbarry** [comment]
Wouldn't you need 

req.params.include?( no )

path is just scriptname + path_info ... you wouldn't even see the query string. Correct?

**Comment by dancinglightning** [comment]
The path the post is to is up there in the log:

: method=POST path=/cgi-bin/php-cgi.bin 

And i am still getting them 

, [2015-05-14T18:19:51.837306 #10712]  INFO -- : method=POST path=/wp-admin/admin-ajax.php format= controller=page action=error_404 status=500 error='ActionContr
oller::InvalidAuthenticityToken:ActionController::InvalidAuthenticityToken' duration=0.71 view=0.00 db=0.00
F, [2015-05-14T18:19:51.839830 #10712] FATAL -- :
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  vendor/bundle/ruby/1.9.1/gems/actionpack-4.1.10/lib/action_controller/metal/request_forgery_protection.rb:176:in `handle_unverified_request'

**Comment by michaeldbarry** [comment]
Ok ... but req.path is just a scalar and in this case would just be

/cgi-bin/php-cgi.bin

right? If that's the case, your blacklist will never return true because you need to inspect params, not path. Am I missing something?

**Comment by michaeldbarry** [comment]
Ahh ... gotcha.

**Comment by dancinglightning** [comment]
Well, that does sound like a good explanation of why i am getting this.
But i off course did nothing but follow instructions, so i feel (maybe wrongly?) that where RackAttack sits should either be automatically before any rails stuff, or in the instructions.

**Comment by michaeldbarry** [comment]
hmmm .. might be a ruby/rails version issue. I'm using rails 4.2 and ruby 2.1.2 ... for it to work for me, I had to rework your example (the return gave an 'LocalJumpError (unexpected return):'  error.

blacklist( 'block admin probes' ) do |req|
  block = false
  ["php" , "jsp" , "cgi", "asp", "cfm," "proxy.txt", "soapCaller", "Win32" , "HNAP1" , "w00tw00t",
    "pma" , "mysql" ,"msd" , "MySQL" , "jmx-console" , "ervlet" , "xml" , "cart" ,"install"].each do |no|
      block = true if req.path.include?(no)
  end
  block
end

that worked as you expect (403 and no 422 for the POST).

**Comment by dancinglightning** [comment]
well @michaeldbarry thanks for looking into it.
I am actually still using 1.9.3 in production, and i am not getting JumpErrors
But i have changed the loop as per example. Even they look the same to me. But maybe it is a freakish ruby bug that is ignored in 1.9 and raised in 2.1.
I updated my server and will let you know in a couple of days. thanks

**Comment by ktheory** [comment]
@dancinglightning: I too suspect a middleware ordering issue as @michaeldbarry suggested.

(@michaeldbarry & @tiegz, thx for looking in to this.)

Rack middleware varies a lot between rails apps. The rack-attack instruction of `config.middleware.use Rack::Attack` works in many cases, but may need to be tweaked in certain apps. Also, it's a matter of developer preference whether rack-attack should run before or after auth token checks. Personally, I like it coming *after* so our app doesn't bother checking throttles for requests we can quickly reject.

Check out http://guides.rubyonrails.org/rails_on_rack.html#configuring-middleware-stack for how to customize the order the app middleware in your app.
