### ISSUE TITLE
Disable the rack-attack log

### ISSUE THREAD

**Issue by gustavovendramini** [kickstarter/rack-attack#130]
Is there any way to disable the Rack Attack logs?

Like:

> Cache read: ...
> Cache increment: ...

**Comment by ktheory** [comment]
@gustavovendramini: Those log messages are not explicitly generated by rack-attack.

I *suspect* it's a side effect of using a low log level (like `debug`) with `Rails.cache`; and any read/increment emits an ActiveSupport::Notification event that generates that log.

I recommend increasing your log level, or modifying the ActiveSupport notification events to not log rack attack messages.
