### ISSUE TITLE
NoMethodError: undefined method `filter' for Rack::Attack::Fail2Ban:Class

### ISSUE THREAD

**Issue by meowist** [kickstarter/rack-attack#131]
I've been using rack-attack successfully for the past year or so--thank you! 

Over the past week, I've gotten this error twice:

`NoMethodError: undefined method 'filter' for Rack::Attack::Fail2Ban:Class`

Here's a [gist](https://gist.github.com/meowist/a9e94a7534910db4237c) of the relevant lines from my rack-attack.rb file where I'm calling the filter method. 

I'm using v 4.2.0. I noticed you released 4.3.0 on 5/22 so perhaps this is related and I should just upgrade?

Thanks for any help!

**Comment by jasonfb** [comment]
sounds like a fluke ruby thing is this is extremely rare.

**Comment by grzuy** [comment]
Hi @meowist 

Are you still experiencing this issue?
If so, still experiencing it with rack-attack 5?

**Comment by meowist** [comment]
Hi @grzuy, Not experiencing this anymore, thank you for checking.

**Comment by grzuy** [comment]
Thank you.
