### ISSUE TITLE
429 OK is returned instead of 429 Too Many Requests

### ISSUE THREAD

**Issue by Aldekein** [kickstarter/rack-attack#133]
Hello,

Here is how I handle throttled responses:

```ruby
Rack::Attack.throttled_response = lambda do |env|
  error_text = 'Too many requests. Please wait for 3 minutes and try again.'

  # we cover our Angular requests and show simple text message to others
  response = env['REQUEST_URI'].ends_with?('.json') ? "{\"success\":false,\"message\":\"#{error_text}\"}" : error_text
  [ 429, {}, [response]]
end
```

Everything is great except this is displayed as 429 OK response in Chrome network console.
This is not a Chrome issue and it could be checked on http://httpstat.us/429 :

![image](https://cloud.githubusercontent.com/assets/671454/8379033/cbd4bd86-1c4f-11e5-830a-48ef638fb6a0.png)

How could I return not only the 429 status but also a valid status description?

**Comment by tiegz** [comment]
@Aldekein from your screenshot like it's returning the correct text (`Too Many Requests`). I also tested with the int `429` as the response code, which resulted in `429 Too Many Requests`.

**Comment by ktheory** [comment]
Good catch, @tiegz.

@Aldekein: looks like things are working as intended. The default throttled response works in many cases, but you can easily customize it if you need. See [this section of the README](https://github.com/kickstarter/rack-attack#responses)

**Comment by Aldekein** [comment]
@tiegz the screenshot is from http://httpstat.us/429 page, not from our server!
Here is a screenshot from server using rack attack with customized response (the code is in my first post):

![image](https://cloud.githubusercontent.com/assets/671454/8408797/9cdbb932-1ea5-11e5-8e0c-f8a4aa52bd87.png)

The ruby log is not very descriptive:

```June 29, 2015 - 01:30:23 PM UTC severity=INFO, Started POST "/password/forgot.json" for 103.30.92.10 at 2015-06-29 13:30:23 +0000```

@ktheory: sorry, but it doesn't :(
Could you confirm that the same throttled_response code returns correct status description for you?
