### ISSUE TITLE
[Question] Range of IPs

### ISSUE THREAD

**Issue by RyanTG** [kickstarter/rack-attack#140]
Sorry for the simple question. We currently block IPs on a per-case basis (adding them via Rails Admin), but are interested in blocking entire country ranges (because for every effective attack, there are truckloads of ineffective ones - and our site is strictly North American users). I'm a front end guy and haven't seen the format of the blacklist. Do you know if a range can be inputted in Rails Admin (example: 2.60.0.0-2.60.31.255)? Any reason why it can't? I guess in general I'm a little confused about the format of a blacklist. When I look them up, they come in multiple varieties (CIDR, etc).

Or perhaps we should start with using your throttle tools rather than blacklisting entire country ranges...

**Comment by pisaacs** [comment]
1) This project is about the **rack-attack** gem. For your Rails Admin questions, you're probably better off asking these on stackoverflow.com or on the Rails Admin project site.  

2) I'm not familiar with your business case to block by countries and how robust this check needs to be. Keep in mind that a mildly sophisticated user can easily bypass this check by leveraging other disposable resources (anonymous networks, proxy servers, etc). In the end, it comes down to the "event" you're trying to mitigate. For example, if you're trying to limit the number of requests to a resource, over a period of time, then rack-attack is a candidate.  

Unless you have a specific issue about the rack-attack gem, then I suggest a collaborator close this issue.

**Comment by RyanTG** [comment]
1 & 2) I know. But thanks. Sorry about asking questions in such a round about way.

What format should blacklists be in? Comma separated? And can they use ranges?

**Comment by ktheory** [comment]
Hi @RyanTG,

Yes, rack-attack can block ranges of IP addresses. The example below uses ruby's [`IPAddr`](http://ruby-doc.org/stdlib-2.2.2/libdoc/ipaddr/rdoc/IPAddr.html) class, and the `..` range operator:

```ruby
# Range example:
(1..10).include? 5 # => true
(0..3).include? 5 # => false

# Block 10.* IPs
RANGE = (IPAddr.new('10.0.0.0').to_i..IPAddr.new('10.255.255.255').to_i)
Rack::Attack.blacklist('block_local_network')  do|req|
  RANGE.include?(IPAddr.new(req.ip).to_i)
end

# Alternatively, if you like netmasks, you can do:
Rack::Attack.blacklist('block_local_network')  do |req|
  IPAddr.new('10.0.0.0/8').include? IPAddr.new(req.ip)
end
```

:cake:

And just my $0.02...blocking whole countries often blocks some legitimate visitors, so I urge you to investigate more targeted ways of mitigating attacks.

**Comment by RyanTG** [comment]
I appreciate it @ktheory. And yeah, I wouldn't want to block legit users, so I will investigate more targeted measures.
