### ISSUE TITLE
Periodically getting error in throttle block

### ISSUE THREAD

**Issue by drewB** [kickstarter/rack-attack#146]
5-10 times per day we get the following stack trace coming out of a throttle block:

    NoMethodError: undefined method `merge' for nil:NilClass

Here is the throttle block:

    throttle('blah blah', limit: 5, period: 5.minutes) do |req|
        contest = req.params[:contest]
        contest[:identifier] if contest.present? && req.post? && req.path == '/contests'
    end

The stack trace points to "contest = req.params[:contest]".  The actual requests that cause the error vary quite a bit.  Not clear to me where the merge call is coming from.  

Any thoughts on what could be causing this?

**Comment by ktheory** [comment]
@drewB that's certainly weird!

You'd have to share more of the stack trace to identify where that `merge` is getting called.

That said, I've seen freely available vulnerability scanning software submit malformed request parameters that can generate errors when calling `Rack::Request#params`. If you took out Rack::Attack, those same requests would likely generate errors later in you app.

I've found it's pragmatic to block them early with a blacklist like:

```ruby
blacklist('malformed') { |req|
    # if req.params raises an error, it's a malformed, unprocessable request.
    begin
      req.params
      false
    rescue
      Rails.logger.info "Rejecting malformed request"
      # Consider returning a '400 Bad Request` response code
      true
    end
  }
```

Closing for now. If you think it's not a malformed request, feel free to re-open with more info.

**Comment by drewB** [comment]
That is very helpful.  Just reviewed the requests and sure enough they are bad (had percentage signs in params).  Thank you!
