### ISSUE TITLE
Not sure why localhost whitelist isn't working for me..

### ISSUE THREAD

**Issue by popup-user** [kickstarter/rack-attack#151]
Hi,
I'm using  rack-attack 4.3.0 with rails 4.2.4 and ruby 2.2.3 and whitelisting my localhost doesn't seem to be working. If I repeatedly refresh my browser, I get 'Retry later' Any ideas on what I might be doing wrong? The url I'm using for development is; http://localhost:3000. Help appreciated! Thanks.

My /config/initilizers/rack-attack.rb looks like this:
```ruby
class Rack::Attack
  throttle('req/ip', :limit => 300, :period => 5.minutes) do |req|
    req.ip # unless req.path.starts_with?('/assets')
  end
  throttle('logins/ip', :limit => 5, :period => 20.seconds) do |req|
    if req.path == '/login' && req.post?
      req.ip
    end
  end
end
Rack::Attack.whitelist('allow from localhost') do |req|
  # Requests are allowed if the return value is truthy
  '127.0.0.1' == req.ip
end
```

**Comment by tiegz** [comment]
@popup-user have you tried debugging `req.ip` in the block to see if it's really `127.0.0.1`. One possibility could be `Rack::Request#ip` being overridden by another gem?

**Comment by popup-user** [comment]
interesting. when I debug, it's showing up as "::1"

**Comment by tiegz** [comment]
@popup-user interesting! I wonder why the `trusted_proxy` regex [here](https://github.com/rack/rack/blob/1.5.5/lib/rack/request.rb#L344-L346) isn't matching it?

**Comment by tiegz** [comment]
(doh, ignore my last comment! Wondering if we shoudl update rack-attack docs to include `::1` now)

**Comment by popup-user** [comment]
@tiegz probably a good idea to include a note about ``'::1' == req.ip``` on macs (and potentially other IPv6-configured devices -- and people can figure out a solution for themselves. I was surprised to see it and not 127.0.0.1, myself.

**Comment by ktheory** [comment]
@popup-user, @tiegz added in #152
