### ISSUE TITLE
Post params missing

### ISSUE THREAD

**Issue by damienbrz** [kickstarter/rack-attack#156]
I have the following
```ruby
Rack::Attack.throttle('req/preview', limit: 3, period: 1.minute) do |req|
  puts "Rack::Attack> #{req.params.inspect}"
  req.params['item_id'] if "preview".in?(req.path) && req.post?
end
```

In my controller I have:

```ruby
def preview
puts "Preview> #{params.inspect}"
...
end
```

When I run the following in my specs:

```ruby
post items_preview_path(:item_id => @item.id, :preview_email => "test@test.com")
```

Here the print in the terminal:
```
Rack::Attack> {"preview_email"=>"test@test.com"}
Preview> {"preview_email"=>"test@test.com", "action"=>"preview", "controller"=>"items", "item_id"=>"1"}
```

I cannot figure out why I don't have access to params[:item_id] in the throttle block.

**Comment by ktheory** [comment]
@damienbrz Good question!

The `item_id` is actually in the request `path` (like, `/item/1234/preview`) from Rack's perspective (not a query or POST param like `req.params` returns). Rails router magic parses it out of the request path and sticks it in the params.

So your throttle should look for the item_id in the path. Here's a completely untested example:

```ruby
Rack::Attack.throttle('req/preview', limit: 3, period: 1.minute) do |req|
  if req.post? && match = req.path.match(/^\/item\/(\w+)\/preview$/)
    match[1]
  end
end
```

**Comment by damienbrz** [comment]
Thanks @ktheory :)
