### ISSUE TITLE
Enable / Disable a throttled rule

### ISSUE THREAD

**Issue by jonatas** [kickstarter/rack-attack#160]
Hi, I'm implementing my custom rules to throttle the bad guys requests.

But, as a experimental feature I want to disable them if some :hankey: happens... I'm planning to use a kind of rolloutable feature, allowing/disallowing it in some time.
 
So,  how can I clear a specific throttled rule in realtime? Is possible?

**Comment by jonatas** [comment]
I find it! 

```ruby
Rack::Attack.throttles.delete "my policy"
```

**Comment by ktheory** [comment]
Great! 🎉
