### ISSUE TITLE
#cache_key for throttle or track?

### ISSUE THREAD

**Issue by jamilbk** [kickstarter/rack-attack#161]
Is there a simple way to get the cache key for a track in Rack::Attack.tracks? I want to check the throttle data in a request other than the matching one. My store is Redis.

If not would you consider a pull request to implement this?

**Comment by ktheory** [comment]
Hi @jamilbk! Thanks for using rack-attack.

Just to clarify, `tracks` don't have cache keys. Developers should treat the cache keys as opaque. I don't think it'd be a good habit to expose them.

Can you think of an alternative approach?

**Comment by jamilbk** [comment]
Thanks for the quick reply!

Hmmm. I'm trying to decouple the tracking of requests from acting on them. For example, I may want to direct new users to a special landing page if greater than X number of users have attempted sign up. So I'd track `POST`s to `/users/registrations`, but in other requests, I would need a helper like `registration_exceeded?` which reads the throttle_data for other requests in the cache.

```ruby
def [](req)
        discriminator = block[req]
        return false unless discriminator

        current_period = period.respond_to?(:call) ? period.call(req) : period
        current_limit  = limit.respond_to?(:call) ? limit.call(req) : limit
        key            = "#{name}:#{discriminator}"
        count          = cache.count(key, current_period)

```

I realize this is a special case and a bit hacky since the cache key is determined by the block given to `throttle()` (discriminator) but in cases where the key isn't ephemeral it'd be nice to be able to retrieve the result of other tracks.

Sorry if this is confusing... maybe I should just store and read these from the DB.

**Comment by ktheory** [comment]
> maybe I should just store and read these from the DB.

:+1:

rack-attack's cache should be treated as ephemeral cache, whereas this sounds like important business logic.
