### ISSUE TITLE
Rack attack is unable to block any ip

### ISSUE THREAD

**Issue by abhinaykumar** [kickstarter/rack-attack#162]
This might be an issue from my side but unfortunately I don't know what is causing this issue. I tried the example given in the readme for blacklist but for some reason its not working for me. I have asked one question here: http://stackoverflow.com/q/35116023/2545197 on StackOverflow regarding the same. It would be great if anyone can answer this question.
Thank you!!

**Comment by ktheory** [comment]
Hi @abhinaykumar, answered on SO. Closing here.

**Comment by abhinaykumar** [comment]
Hey @ktheory thank you so much for your quick response, but I have already tried the example given and system is still unable to block the IP. I have updated my question with the same. I really appreciate that you have taken some time to look at.
