### ISSUE TITLE
What happens if the Rails cache store is set to :file_store?

### ISSUE THREAD

**Issue by tirdadc** [kickstarter/rack-attack#164]
http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore

Will Rack Attack still work then? Or should I then set `Rack::Attack.cache.store` to something else that's memory backed?

**Comment by ktheory** [comment]
Using FileStore means that the cache is local to each server rather than shared. As a result, rack-attack may appear to work fine for a single server, but won't accurately enforce throttle limits with multiple servers.
