### ISSUE TITLE
Specifying throttling parameters in routes table?

### ISSUE THREAD

**Issue by nadavb** [kickstarter/rack-attack#167]
Anyone thought of this feature? 
Instead of specifying in the rack-attack.rb all the throttles per each route, define the parameters directly in the routes table, and then process them one by one in the rack-attack.rb...

**Comment by ktheory** [comment]
Hi @nadavb,

I don't understand the suggestion. Can you clarify?

Keep in mind that not all throttles are per route. They could be requests per IP address, or requests per user agent.

Also, what's the routes table of a generic rack application?

**Comment by nadavb** [comment]
I'm talking about Rails.

So you'd be able to write in routes.rb table something like:
get "test" => 'main#test', :throttle => [:ip => true, :limit => 50 , :period => 10.minutes]

**Comment by ktheory** [comment]
Thanks for clarifying. :smile: 

This could be implemented as an extension to rack-attack, so that seems like a natural place for you to build out the idea.

In your example, I'd think about how to specify the discriminator (`:ip => true`), and how that could be make more artibtrary.

Closing this out since there's nothing to change w/ `rack-attack`.

**Comment by nadavb** [comment]
So that should be implemented in a fork, and not directly to this gem?

**Comment by ktheory** [comment]
It's not a fork. By "extension", I meant a whole new ruby gem that depends
on `rack-attack` and adds additional features.

Rack::Attack::RateLimit is an example:
https://github.com/jbyck/rack-attack-rate-limit

**Comment by nadavb** [comment]
Thanks. 
In the rack-attack.rb file (Rack::Attack), where I define all the throttles, I don't have access to my routes file via Rails.application.routes - do you know why? Maybe it's higher in the stack? Is there a way to access the routes file, so I can pre-process and define the throttles, dynamically by analyzing the routes file?

**Comment by nadavb** [comment]
I've managed to create a solution.
In the routes.rb you can write:

`get "apicall", :attackip => [{:t => [30, 1.minutes]}]`

And in the rack-attack.rb add:

`file = File.read(File.expand_path("../../routes.rb", __FILE__))
  file = file.split("\n")[1..-2].join("\n") # remove first line and last line

  myroutes = Rails.application.routes
  myroutes.prepend do
    eval(file)
  end
  myroutes.clear!
  counter = 0
  myroutes.named_routes.routes.each do |route| # For each route
    extractedroute = route[1]
    if extractedroute.defaults[:attackip] != nil
      attack = extractedroute.defaults[:attackip]
      path = extractedroute.path.spec.left.to_s
      attack.each do |method| # For each Attack method
        counter = counter + 1
        if method[:t] != nil # If we have a throttle
          throttlename = 'throttle-'+counter.to_s+'-'+path
          Rails.logger.error 'Creating throttle: '+throttlename
          throttle(throttlename, :limit => method[:t][0], :period => method[:t][1]) do |req|
            if req.path.start_with?(path)
                req.ip
            end
          end # EOF throttle command

        elsif method[:a] != nil
          allow2banname = 'allow2banname-'+counter.to_s+'-'+path
          Rails.logger.error 'Creating allow2ban: '+allow2banname
          Rack::Attack.blacklist(allow2banname) do |req|
            Rack::Attack::Allow2Ban.filter(req.ip, :maxretry => method[:a][0], :findtime => method[:a][1], :bantime => method[:a][2]) do
              if req.path.start_with?(path) # Only if trying to reach again to the check path, block the user
                true
              end
            end
          end
        end # EOF Allow2Ban directive
      end # For all attack mechanisms
    end # If we have an attack directive
  end # EOF for all routes
  myroutes.prepend.clear
`
