### ISSUE TITLE
Throttling (or banning) on invalid route

### ISSUE THREAD

**Issue by nadavb** [kickstarter/rack-attack#171]
How do I ban somebody who has tried GETing into a non-existent route 20 times in a minute?

**Comment by nadavb** [comment]
Okay found the solution.
In the rack-attack.rb I add the Allow2Ban
` Rack::Attack.blacklist('allow2banname-notfoundpath') do |req|
    Rack::Attack::Allow2Ban.filter(req.ip, :maxretry => 15, :findtime => 5.minutes, :bantime => 24.hours) do
      false # I am going to increase the counter programmatically inside the controller... (Application_controller.rb)
    end
  end`

And in the controller that handles the unfounded-path I increase the counter programmatically.

`Rack::Attack::Allow2Ban.filter(request.remote_ip, :maxretry => 15, :findtime => 5.minutes, :bantime => 24.hours) do
      true
    end`

**Comment by ktheory** [comment]
@nadavb yup, that's a way to do it. :smile: 

Rack::Attack can only inspect *request* attributes, and generally doesn't know about *response* attributes (like a 404 Not Found); so implementing this is going to take some app changes on your part.
