### ISSUE TITLE
Throttling verbiage incorrect?

### ISSUE THREAD

**Issue by jkmcrg** [kickstarter/rack-attack#172]
In the first throttling block comment, it states:
```
# If the return value is truthy, the cache key for the return value
# is incremented and compared with the limit.
```
Shouldn't this say:
```
# If the return value is truthy, the cache value for the returned key
# is incremented and compared with the limit.
```
I could be incorrect, but it threw me off, anyway.

**Comment by jkmcrg** [comment]
Putting executable commented code in the ruby block made me question if that was a value I should return, whereas in the initializer docs, you have a comment above the throttle block saying:
```
# Key: "rack::attack:#{Time.now.to_i/:period}:req/ip:#{req.ip}"
```
Which gets the point across better that it would be the key generated using the return value of the block, and not something I should write myself.

**Comment by ktheory** [comment]
@jkmcrg Good points! I'd welcome a pull request improving the documentation. :wink: 

As for disambiguating the "cache key" or "cache value"; I'd suggest the "value of the cache key".

**Comment by ktheory** [comment]
Closing pending a PR
