### ISSUE TITLE
Log rejected requests?

### ISSUE THREAD

**Issue by aurcioli-handy** [kickstarter/rack-attack#175]
Is there a way to know when a request has exceeded a throttle and then trigger a logging event for that? I know we can track but I would like to know only when rack attack is blocking/rejecting a request.

**Comment by ktheory** [comment]
@aurcioli-handy yup, that's totally possible. :smile: 

It works by using ActiveSupport Notifications ([see this example](https://github.com/kickstarter/rack-attack/blob/master/examples/instrumentation.rb)).

Here's an example subscriber that logs when a request is blacklisted or throttled:

```ruby
LOGGER = Logger.new("log/rack-attack.log")
ActiveSupport::Notifications.subscribe('rack.attack') do |name, start, finish, request_id, req|
  if [:throttle, :blacklist].include? req.env['rack.attack.match_type']
    LOGGER.info [match, req.ip, req.request_method, req.fullpath, ('"' + req.user_agent.to_s + '"')].join(' ')
  end
end
```

**Comment by aurcioli-handy** [comment]
Awesome, thankyou!

**Comment by jageschiff** [comment]
Fixed a couple of errors: `match` not defined, and `:blacklist` should be `:blocklist`.  Also generalized it to track all requests.

```
LOGGER = Logger.new("log/rack-attack.log")
ActiveSupport::Notifications.subscribe('rack.attack') do |name, start, finish, request_id, req|
  msg = [req.env['rack.attack.match_type'], req.ip, req.request_method, req.fullpath, ('"' + req.user_agent.to_s + '"')].join(' ')
  if [:throttle, :blocklist].include? req.env['rack.attack.match_type']
    LOGGER.error(msg)
  else
    LOGGER.info(msg)
  end
end
```

**Comment by markixnim** [comment]
@jageschiff 

I'm wondering where would you put this code? Thanks.

**Comment by jageschiff** [comment]
this is the content the file in my application `config\initializers\rack_attack_logger.rb`

**Comment by md-farhan-memon** [comment]
After using the [above code](https://github.com/kickstarter/rack-attack/issues/175#issuecomment-288898133) I was getting the following error:

> **NoMethodError (undefined method `env' for #<Hash:0x005569f95f02b8>)**

so posting updated code for others who may encounter the same.

    LOGGER = Logger.new('log/rack-attack.log')
    ActiveSupport::Notifications.subscribe('rack.attack') do |_name, _start, _finish, _request_id, req|
      req = req[:request]
      msg = [req.env['rack.attack.match_type'], req.ip, req.request_method, req.fullpath, ('"' + req.user_agent.to_s + '"')].join(' ')
      if %i[throttle blocklist].include?(req.env['rack.attack.match_type'])
        LOGGER.error(msg)
      else
        LOGGER.info(msg)
      end
    end

**Comment by grzuy** [comment]
Hi @md-farhan-memon,

Thanks for the comment.

Indeed, that's because of the change in https://github.com/kickstarter/rack-attack/pull/256, which was first released in rack-attack v6.0.

**Comment by bjhess** [comment]
A small tweak that I might suggest for the next person who happens on to this thread:

```ruby
LOGGER = Logger.new("log/#{Rails.env}-rack-attack.log")
```

This gets your log file names in line with Rails logs: `development-rack-attack.log`, `test-rack-attack.log`, `production-rack-attack.log`, etc.

**Comment by ktheory** [comment]
@bjhess et al -- thanks for the improvements. I updated the example above.
