### ISSUE TITLE
Where is Track information saved?

### ISSUE THREAD

**Issue by sergiotapia** [kickstarter/rack-attack#176]
Reading this article: https://www.kickstarter.com/backing-and-hacking/rack-attack-protection-from-abusive-clients

If I were to execute this in a Rails app:

```
class Rack::Attack
  track('regular_user') do |req|
    true # Just for testing, let's track everything.
  end
end
```

Where is that track information saved to? Where can I query the data saved?

**Comment by ktheory** [comment]
:wave: Hi @sergiotapia,

Track info is added to the request as:

```
env["rack.attack.matched"]
env["rack.attack.match_type"]
```

See the ActiveSupport example [in the README](https://github.com/kickstarter/rack-attack#tracks).
