### ISSUE TITLE
using rack-attack to throtle requests to grape Api

### ISSUE THREAD

**Issue by sachinsaxena1996** [kickstarter/rack-attack#177]
I have created a CustomLimiter class in lib: Its working for non grape api guests but the throttling is not working for grape api get_users. The flow is going inside the if condition for grape api where its returning req.ip. Please suggest why Customlimiter is not working for grape api

class CustomLimiter < Rack::Attack
  def CustomLimiter.throttle_request(upload_type)
    if upload_type == 'guests'
      rate_cutter = ApiConfig.where(api_code_name: 'post_guest_upload').select(:max_no_of_requests, :time_period_in_secs).first
      Rack::Attack.throttle('api/json/upload/guests/ip', :limit => rate_cutter.max_no_of_requests, :period => rate_cutter.time_period_in_secs.seconds) do |req|
        if req.path == '/api/json/upload/guests' && req.post?
          req.ip
        end
      end    
    elsif upload_type == 'get_users'
      rate_cutter = ApiConfig.where(api_code_name: 'get_users').select(:max_no_of_requests, :time_period_in_secs).first
      Rack::Attack.throttle('api/users/ip', :limit => rate_cutter.max_no_of_requests, :period => rate_cutter.time_period_in_secs.seconds) do |req|        
        if req.path == '/api/users' && req.get?
          req.ip          
        end
      end
    end

  end
end

**Comment by ktheory** [comment]
Hi @sachinsaxena1996,

This looks like a pretty complicated example; and I can't see where you're loading `CustomLimiter` as rack middleware.

To debug, I recommend you start with some of the examples in the README with an easily testable limit. For example, start with a regular `Rack::Attack.throttle('req/ip', limit: 1, period: 1) { req.ip }`.

Then start customizing it towards your use case of loading dynamic throttles from a datastore, and using a custom subclass. By making several small changes and confirming each one works as expected, it'll be more obvious where your implementation stops working.

I'll close this issue b/c I doesn't seem like there's any action to take with Rack::Attack.

**Comment by sachinsaxena1996** [comment]
Hi, 
The throtting for guest api is working but when I change the limits it still reflects the previous throttle values. whereas its working fine for upload_type == 'guests', if I change limits its reflected in api.

custom_limiter.rb is in lib folder which is loaded in application.rb
I have moved below from initailzer/rack-attack.rb to custom_limiter.rb so that I can use values from db for limits in runtime, its working in above code for non-grape api 'guests' but for grape api its still taking the values which are initialised when i strat rails server , then even if change the limits from database its stiill reflecting the old throttle limits. Please suggest why its not working for grape api

 throttle('api/json/upload/guests/ip', :limit => 1, :period => 120.seconds) do |req|
    if req.path == '/api/json/upload/guests' && req.post?
      rate_cutter.max_no_of_requests
      rate_cutter.time_period_in_secs
      req.ip
     end
   end

**Comment by gottfrois** [comment]
You might be interested by https://github.com/gottfrois/grape-attack
