### ISSUE TITLE
Rack-attack is not throttling requests in a consistent manner

### ISSUE THREAD

**Issue by sachinsaxena1996** [kickstarter/rack-attack#180]
Hi,
I am usning rack-attack gem to throttle the requests. It works fine on my local machine. but on other env it is showing inconsistent behaviour.
I have set the max number of request 2 in 60 secs but sometimes it allows 6 or more requests and does not throttles the requets after second request. Please suggest what may be the possible reason reason for the same

**Comment by ktheory** [comment]
What cache store are you using? For rack-attack to work correctly, you need a shared cache store like Redis or Memcache.

The behavior you're seein is expected if you're using a per-server cache like MemoryStore or FileStore on multiple servers.

**Comment by sachinsaxena1996** [comment]
I was using MemoryStore. How I can use redis for the same. When I have configured redis for same I am getting NoMethodError (undefined method `increment' for #<Array:0x00000002328820>): Please suugest why I am getting this error while using redis on localhost.

**Comment by sachinsaxena1996** [comment]
Hi ,

I have coommented below line in rack-attack.rb, and its now taking Rails.cache [i.e redis in my app by default]. Its working now.

**Comment by sachinsaxena1996** [comment]
Hi,
It was working fine after commenting below line in rack-attack.rb (Enviroment having only one redis server).
#Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new

But when the same enviroment have 2 redis servers (i.e Master and slave), API rate limit is not working.
Please give your suggestion if any configuration is required when I am using two Redis servers [i.e Master & Slave]

**Comment by arrk-shoba** [comment]
Hi Aaron,
In the test environments where we had only one Redis server, rack-attack worked well for us. In staging environment, we have multiple Redis servers (1 master and 1 slave) - in this environment, rack-attack is not working. Is it a issue with the rack-attack or we are missing any configuration?
Any help or suggestion is highly appreciated.

**Comment by jogaco** [comment]
I found that the `redis-cli monitor` command is a life saver to check if it works fine.

Thanks to rack-attack, I've caught and banned my first badly behaved crawler!

**Comment by ktheory** [comment]
Thanks @jogaco, good suggestion.

@arrk-shoba & @sachinsaxena1996: it sounds like you each have an issue with how your app is configuring the Rack::Attack.cache client. I'm not able to debug that for you.

I'm going to close this b/c this seems like something to work around in the client app rather than in rack-attack.
