### ISSUE TITLE
POST params missing

### ISSUE THREAD

**Issue by pedrocunha** [kickstarter/rack-attack#189]
Hey guys, I'm having issues detecting the POST params. Unfortunately the issue is different than https://github.com/kickstarter/rack-attack/issues/156. 

Here is the problem:

```ruby
# config/initializers/rack-attack.rb
class Rack::Attack
  blacklist('...') do |req|
        # set pry session here, see below
  end
end
```

Do a POST on a Rails route with some params and pry stops inside the blacklist block:

```ruby
[1] pry(Rack::Attack)> req.env["action_dispatch.request.request_parameters"]
=> {"email"=>"foo@gmail.com", "password"=>"pasdasda"}
[2] pry(Rack::Attack)> req.params
=> {}
```

As you can see `req.env` has the request params, but the same are not present on `#params`. Am I missing something out? 

Thanks in advance,
Pedro

**Comment by pedrocunha** [comment]
Turns out this is an issue with the middleware and rack, and not Rack::Attack.

**Comment by ktheory** [comment]
@pedrocunha 👌 thanks for updating the issue.

**Comment by dorthwein** [comment]
Is it not possible to get post params or is there a config option somewhere?

**Comment by pduey** [comment]
> EDIT: To get the post params you need to do
> 
> `params = JSON.parse( req.body.read )`

After calling req.body.read, you might need to req.body.rewind since it's an IO buffer.

**Comment by tferrerITBA** [comment]
You can also just `include ActiveSupport` into `Rack::Attack` to avoid parsing the body manually.

**Comment by taylorbrooks** [comment]
@pduey What are the reasons for using `read/rewind` vs. `string` on `StringIO`?

**Comment by pduey** [comment]
@taylorbrooks in my case req.body is not a StringIO, it's a Puma::NullIO object.

Anyway, I've done some upgrades and now to get regular POST params I use simply req.params, and to get JSON POST params, I use ActionDispatch::Request.new(req.env).params per [https://github.com/kickstarter/rack-attack/issues/399](url)

**Comment by l4cr0ss** [comment]
> > EDIT: To get the post params you need to do
> > `params = JSON.parse( req.body.read )`
> 
> After calling req.body.read, you might need to req.body.rewind since it's an IO buffer.

Another way to do this, what with StringIO being a way to pretend that a string is really a stream of bytes, is to access the underlying buffer directly with `req.body.string`, and that way you won't need to rewind the stream pointer.
