### ISSUE TITLE
redis gem only expects one argument in the `get` method

### ISSUE THREAD

**Issue by monfresh** [kickstarter/rack-attack#190]
Hi. I've noticed other similar issues, but I couldn't get a definitive answer. When I implement a `Fail2Ban` filter, I get this error:

```
ArgumentError - wrong number of arguments (given 2, expected 1):
13:05:52 web.1    |   redis (3.3.0) lib/redis.rb:860:in `get'
13:05:52 web.1    |   /Users/moncefbelyamani/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
13:05:52 web.1    |   rack-attack (4.4.1) lib/rack/attack/store_proxy/redis_store_proxy.rb:16:in `read'
13:05:52 web.1    |   rack-attack (4.4.1) lib/rack/attack/cache.rb:23:in `read'
13:05:52 web.1    |   rack-attack (4.4.1) lib/rack/attack/fail2ban.rb:26:in `banned?'
13:05:52 web.1    |   rack-attack (4.4.1) lib/rack/attack/fail2ban.rb:10:in `filter'
```

The README implies that I should be able to use the `redis` gem (v3.0.0+), but it looks like it's not supported because `RedisStoreProxy#read` passes in 2 arguments. From reading the other issues, it seems like I would need to add another dependency to my app for this work, namely the `redis-store` gem.

What is the purpose of the `raw: true` option, and is it essential? Could it be made optional? Is this a bug in the `redis` gem, or is it not required of it to accept a second argument? If the second argument is optional, then could rack-attack please update the `read` method such that it's compatible with the `redis` gem?

Thanks!

**Comment by sgtpepper43** [comment]
I'm also seeing this issue with the `setex` command, you're passing in four arguments when it expects three. I don't know if it's _actually_ a problem, but I'm using bugsnag and it logs that error out quite a bit. Would appreciate a little clarification.

**Comment by kgleong** [comment]
I'm also seeing a similar error with the `setex` method.

My rack-attack Redis store configuration in `application.rb`:

```
      redis = Redis.new(
        host: redis_config[:host],
        port: redis_config[:port],
        db: redis_config[:db],
      )

      Rack::Attack.cache.store =
        Rack::Attack::StoreProxy::RedisStoreProxy.new(redis)
```

**Comment by ryantm** [comment]
It looks like https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack/store_proxy/redis_store_proxy.rb#L22 is wrong because it passes raw: true to redis, and it doesn't seem like the redis gem supports that.

**Comment by ryantm** [comment]
@ktheory How are these proxies supposed to work anyway? They seem to swallow all the errors that might come from below without bothering to log them.

**Comment by ryantm** [comment]
I thought this was using the redis gem directly, but it is actually using the redis-store gem which has the appropriate interface.

**Comment by grzuy** [comment]
Hi @monfresh, thank you for the issue report.

Can you please share your rack-attack store config if you still facing this issue?

**Comment by grzuy** [comment]
For the record, plain `Redis` support added in `rack-attack 5.4.0`.
