### ISSUE TITLE
Shared IP Issue.

### ISSUE THREAD

**Issue by kathuriaranjan** [kickstarter/rack-attack#192]
How does this gem manage to throttle shared ip?

Suppose an app has login form with rate limitation of 5 requests :-
`
  throttle('logins/ip', :limit => 5, :period => 20.seconds) do |req|
            .....
  end

`
Take a scenario where users are accessing the app via shared network (workplace/office) and some users (>5) say 10 tries to access the login form same time. 
Now as they are sharing same IP (external) therefore this will cross the rate limit.

How to tackle this down?

**Comment by ktheory** [comment]
Hi @kathuriaranjan:

I don't know of good, general way to distinguish many users sharing the same IP address.

I choose my throttle limits such that even if there are many users sharing the IP, legitimate use does not reach the throttle limit. Only clear abuse triggers the throttle.

(Also note that it's unlikely all 10 users would try to log in at the same time. It would take coordination for 10 people to all log in during the a 20-second time period.)
