### ISSUE TITLE
deprecated Ahoy::Throttle.whitelisted? method

### ISSUE THREAD

**Issue by although2013** [kickstarter/rack-attack#197]
Hi there
`Ahoy::Throttle.whitelisted?` will cause `ArgumentError: wrong number of arguments` exception since I update to rack-attack 5.0.0.

please take a look at this line:
https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack.rb#L73

`safelisted?` method doesn't pass a parameter, is it designed for? We just can't use the deprecated method anymore if upgrade to rack-attack 5.0.0?

I'm not familiar with this gem and sorry for my poor English, please kindly give me some feedback.

Thanks
Howard

**Comment by ktheory** [comment]
@although 2013, yup, you're right. It's a bug.

I'll try to get a fix out in the next few days.

In the meantime, a workaround is to stick with version 4; or rename 'whitelist' to 'safelist' in v5.
