### ISSUE TITLE
For some reason rack::attack does not work.

### ISSUE THREAD

**Issue by extempl** [kickstarter/rack-attack#201]
Maybe we're doing something wrong, but this don't looks well for me: https://cl.ly/2L3I1s1N0e1Q

in `rack-attack.rb` we have

```
   class Rack::Attack::Request < ::Rack::Request
    def remote_ip
      @remote_ip ||= (@env["action_dispatch.remote_ip"] || ip).to_s
    end
  end

  class Rack::Attack
    throttle('req/ip', :limit => 300, :period => 5.minutes) do |req|
      req.remote_ip # unless req.path.starts_with?('/assets')
    end
  end
```

From logs it looks like it increments entries, but nothing is throttled.

**Comment by ktheory** [comment]
Hi @extempl,

Please check that you're using a suitable cache store (like memcache or redis).

**Comment by extempl** [comment]
@ktheory we're using Rails.cache, as default. Why doesn't it work with it? I understand that in my case there are three caches (per dyno), but it is still a lot requests.

**Comment by ktheory** [comment]
@extempl Make sure your `Rails.cache` is set to a shared cache store, like memcache or redis.
