### ISSUE TITLE
Notification service.

### ISSUE THREAD

**Issue by 23ranjan** [kickstarter/rack-attack#203]
Hi @ktheory 

Can we have a notification feature which will send a notification (similar as cloudwatch) when rate limitation is reached for a particualr ip?

Thanks,

**Comment by ktheory** [comment]
@23ranjan Sure. Rack::Attack emits notifications events that you can hook in to and process however you want (like email them, send them to chat, etc). See [the docs on the notification API](https://github.com/kickstarter/rack-attack#logging--instrumentation) to get started.
