### ISSUE TITLE
run Rack::Attack.blocklist before rack-rewrite

### ISSUE THREAD

**Issue by agiambro** [kickstarter/rack-attack#212]
I'm using the rack-rewrite gem with this also in application.rb:  

config.middleware.insert_before(Rack::Runtime, Rack::Rewrite) { r301 ..., method: :get }

This is taking precedence over Rack::Attack.blocklist for a particular incoming IP.  Anyway to run blocklist before the rewrite rule fires?

**Comment by grzuy** [comment]
Hi Anthony,

What is the output you get when you run

```
$ rake middleware
```

for your rails app?

**Comment by grzuy** [comment]
Closing for now for lack of information and activity.

Please let me know if you still experiencing the issue so we can re-open.
