### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by ktheory** [kickstarter/rack-attack#219]
:wave: Welcome friends of Rack::Attack,

This project has grown to be more than I can support by myself. I'm looking to add some maintainers.

### What I'm looking for from you:

1. Be a helpful and welcoming voice when responding to GitHub issues and pull requests. Today's newbies are tomorrow's core contributors.
2. Exercise clear judgement about what should and should not be a feature of Rack::Attack, and strive to improve Rack::Attack's code quality.

### Roadmap

Feel like jumping in and writing code & documentation? Here are some suggestions for things to work on:

- Make it easier for new users to debug misconfigured cache stores & rules
- Reconsider the proxy pattern used to smooth over differences in cache stores. Is there a simpler, more robust way to support disparate stores?
- Keep Rack::Attack up-to-date with community conventions, and test against with the latest gem dependencies & ruby versions

Please leave a comment below if you're interested!

**Comment by oyinloye-ai** [comment]
Hi ktheory, I am a rookie rail developer but will be interested in being a maintainer. Please buzz me on the way forward. Thanks.

**Comment by ktheory** [comment]
@oyinloye-ai Awesome, and welcome. 👋 

The next step would be to chime in on the open issues with fixes, workarounds, or requests for clarifying information.

**Comment by giubueno** [comment]
Hey pick me! I love this gem.

**Comment by tjnet** [comment]
I love this gem too 😄 
I want to contribute this project!

**Comment by jasonfb** [comment]
👍

**Comment by buck3000** [comment]
Love the gem, definitely interested
