### ISSUE TITLE
How to disable rack-attack for running a larger test suite

### ISSUE THREAD

**Issue by DarthHater** [kickstarter/rack-attack#220]
Rack-attack's functionality works great, and in fact too good! After running and throttling, the rest of our test suite starts failing. Is there a way to disable rack-attack in portions of our test suite? If this is in the docs I can't quite tell. Right now we are using safelisting to get past the issue, but I was more curious if that's the right approach, or if some other mechanism exists. Thanks!

cc/ @lomky

**Comment by Kennnedu** [comment]
You can set middleware only need environment and remove config.middleware.use Rack::Attack from application.rb

example: 
```
# config/environments/production.rb 
	Rails.application.configure do
		config.middleware.use Rack::Attack
	end
```

**Comment by lomky** [comment]
@kennnedu nifty. How do you test it in that set up?

**Comment by Kennnedu** [comment]
@lomky it work for me)

**Comment by shaneog** [comment]
@lomky Check this out for inserting middleware for a test: http://devnull.absolventa.de/2014/10/24/dynamically-insert-rack-middleware-during-test/

**Comment by brandoncc** [comment]
I tried that solution but couldn't get it to work on Rails 5.1. I found this to be easier:

```ruby
# Add this in the throttle definition
throttle = false if Rails.env.test? && !ENV["THROTTLE_DURING_TEST"]
```

```ruby
# add this to your spec block
before(:all) do
  ENV["THROTTLE_DURING_TEST"] = "true"
end

after(:all) do
  ENV.delete("THROTTLE_DURING_TEST")
end

after do
  Rails.cache.clear
end
```

After doing this, you can have the `Rack::Attack` middleware in your test environment all the time.

**Comment by jasonfb** [comment]
We just have a big old ```if !Rails.env.development? && !Rails.env.test?``` right inside of the Rack::Attack class definition. The reason we need to disable it in dev too is because dev makes requests for each asset, quickly overfilling the throttle. 


We have this gem enabled on our staging server(s) and production servers only. Occasionally I enable it in dev (like when I'm debugging it), but generally I don't think about it

**Comment by joshuapinter** [comment]
What we ended up doing is adding `config.middleware.use Rack::Attack` to each of the environment files (e.g. `development.rb`, `test.rb`, `staging.rb` and `production.rb`) and then just commenting it out for `test.rb`. This allows you to easily see where it is enabled and where it is not. 

We decided to leave it enabled in development to uncover any issues that they might also be facing in Production or Staging.

**Comment by grzuy** [comment]
Sounds like the original question was responded. Thanks everyone for chiming in!

For anyone interested in this topic check out https://github.com/kickstarter/rack-attack/issues/301

**Comment by grzuy** [comment]
> You can set middleware only need environment and remove config.middleware.use Rack::Attack from application.rb
> 
> example:
> 
> ```
> # config/environments/production.rb 
>   Rails.application.configure do
>     config.middleware.use Rack::Attack
>   end
> ```

Starting with v6.2.0, you can now `Rack::Attack.enabled = false` instead.
