### ISSUE TITLE
Safelist is not working

### ISSUE THREAD

**Issue by giedriusr** [kickstarter/rack-attack#224]
Hello,

I am using rack-attack for rate limiting in my rails application.

My rack_attack.rb initializer looks like this:

```ruby
ActiveSupport::Notifications.subscribe('rack.attack') do |name, start, finish, request_id, req|
  Raven.capture_message(
    'IpRateLimit',
    logger: 'ip_rate_limit',
    level: 'warning',
    extra: {
      error_message: "#{req.ip_address} has been rate limited for url #{req.url}",
    }
  )
end

class Rack::Attack
  class Request < ::Rack::Request
    def ip_address
      forwarded_ip_address || env['action_dispatch.remote_ip'].try(:calculate_ip) || remote_ip || ip
    end

    def forwarded_ip_address
      ips = env['HTTP_X_FORWARDED_FOR']

      if ips.presence
        ips.split(',').first.presence
      else
        nil
      end
    end
  end

  # Throttle all requests by IP (500rpm)
  throttle('req/ip', limit: 500, period: 1.minute) do |req|
    req.ip_address
  end

  safelist('allow from localhost, jenkins & office') do |req|
    # Requests are allowed if the return value is truthy
    ips = %w(127.0.0.1 ip1 ip2)
    ips.include?(req.ip) || ips.include?(req.ip_address)
  end
end

```

We're using our application quite often from backend and other places like metrics, etc.. So I've added those IPs to safelist and I prefer not to limit those requests. But either I do not understand how it works either it doesn't work the way I expect. We live under Google Cloud Platform with their Load Balancer, that's why I've modified the Rack Attack class to calculate the proper IP of the request. When the IP Rate Limit is reached, it is being tracked by `ActiveSupport::Notifications.subscribe('rack.attack')` and says that "correct IP" (real IP of the user, not the LB IP) has been rate limitted, means, that the IP is taken properly. But can't understand why my safelist doesn't work.

Environment:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
$ rails -v
Rails 4.2.7.1
$ bundle | grep 'rack-attack'
Using rack-attack 5.0.1
```

Anyone else is having similar issues?

Thanks

**Comment by srt32** [comment]
Does the localhost (`127.0.0.1`) safelisting work as expected?

**Comment by giedriusr** [comment]
Yes.

**Comment by Youngv** [comment]
Same situation, request never get into the safalist block

**Comment by Youngv** [comment]
@giedriusr It seems use safelist without blocklist not work, when use safelist and blocklist together work well.

**Comment by giedriusr** [comment]
@Youngv what do you use inside the blocklist?

**Comment by Youngv** [comment]
@giedriusr I think you can separate your code like this
```ruby
safelist('allow from localhost') do |req|
  '127.0.0.1' == req.ip || '::1' == req.ip
end

blocklist('not allow which not from jenkins & office') do |req|
  # Requests are allowed if the return value is truthy
  ips = %w(ip1 ip2)
  ips.exclude?(req.ip)
end
```

**Comment by giedriusr** [comment]
@Youngv Yeah, but what if I don't want to block anyone right now?

**Comment by jogaco** [comment]
I recommend you use redis-cli monitor and then you'll see what's going on.

**Comment by mickael-palma-argus** [comment]
Hi, 

+1 for me here is my Rack::Attach config :
```ruby
require 'active_support/cache/dalli_store'

class Rack::Attack
  # Config caching (Memcached used when many instances need a shared cache)
  if ENV['MEMCACHEDCLOUD_SERVERS']
    Rack::Attack.cache.store = ActiveSupport::Cache::DalliStore.new(
      ENV['MEMCACHEDCLOUD_SERVERS'].split(','),
      username: ENV['MEMCACHEDCLOUD_USERNAME'],
      password: ENV['MEMCACHEDCLOUD_PASSWORD'])
  else
    Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new
  end

  # your custom configuration...
  Rack::Attack.throttle('req/ip', limit: (ENV['RACK_ATTACK_LIMIT'] || 3500).to_i, period: 15.minutes) do |req|
    req.ip
  end

  Rack::Attack.throttled_response = lambda do |_env|
    # name and other data about the matched throttle
    body = {
      "errors": [
        {
          "title": 'max allowed request reached',
          "detail": 'you have been doing too many request in a short laps of time, please wait for 15 minutes',
          "id": 'null',
          "href": 'null',
          "code": 'TOO_MANY_REQUESTS',
          "source": 'All resources',
          "links": 'null',
          "status": 429
        }
      ]
    }

    # if you Use 503 because it may make attacker think that they have successfully
    # DOSed the site. Rack::Attack returns 429 for throttling by default
    Rack::Response.new(body.to_json, 429, 'Content-type' => 'application/vnd.api+json').finish
  end
  Rack::Attack.safelist('allow from localhost') do |req|
    # Requests are allowed if requests provide from localhost (like in test env)
    '127.0.0.1' == req.ip
  end

  Rack::Attack.safelist('allow pvo without limit') do |req|
    PvoWhitelister.new(ip: req.ip).whitelisted?
  end
end

```
`whitelisted?` return a boolean

My whitelisted user get a 429 error and my other users too !
I cannot find a way to debug this.
Any tips ?

**Comment by jogaco** [comment]
I do not have any problems with safelist.
Don't know about memcache, but redis has a cool feature: you can see what's going on with `redis-cli monitor`
With it, you will see every request to redis

**Comment by mickael-palma-argus** [comment]
Thanks for getting back to me and for this gem ;-)

I spent most of the night with this issue.
The root of the problem is the Heroku load balancer IP !

Every client using my API go through heroku router so rack_attack read the REMOTE_ADDR header in stead of the one in the X-Forwarded-For.

So I monkey patch Rack::Attack::Request to handle this Heroku gotcha to say the leat 
```ruby
class Rack::Attack
  # your custom configuration...
  throttle('req/ip', limit: (ENV['RACK_ATTACK_LIMIT'] || 3500).to_i, period: 15.minutes) do |req|
    req.real_client_ip
  end

  safelist('allow from localhost') do |req|
    # Requests are allowed if requests provide from localhost (like in test env)
    req.localhost?
  end

  safelist('allow pvo without limit') do |req|
    req.pvo_ip?
  end
end

class Rack::Attack::Request < ::Rack::Request
  def localhost?
    real_client_ip == '127.0.0.1'
  end

  def pvo_ip?
    PvoWhitelister.new(ip: real_client_ip).whitelisted?
  end

  def real_client_ip
    return ip if env['HTTP_X_FORWARDED_FOR'].blank?
    client_ip_from_headers
  end

  private

  def client_ip_from_headers
    env['HTTP_X_FORWARDED_FOR'].split(',').map(&:strip).first
  end
end
```

I think it would nice to mention that specific case in the documentation since I think I'm not the only one using heroku 😄 
I hope the time I spent on this will be beneficial for others.

Thank you

**Comment by giedriusr** [comment]
Closing this down.

**Comment by NeoElit** [comment]
Sorry for disturbing an old thread, might be worth it.
@mickael-palma-argus, @giedriusr  following code could break rack-attack's purpose as client will be able to tweak X_FORWARDED_FOR header. 
```ruby
def client_ip_from_headers
  env['HTTP_X_FORWARDED_FOR'].split(',').map(&:strip).first
end
```
You should probably strip the trusted proxies from HTTP_X_FORWARDED_FOR and choose the right most one from remaining (assuming trusted proxies/load balancers are appending IP to the end of HTTP_X_FORWARDED_FOR).
It would've been nice if we could just use remote_ip of ActionDispatch::Request (provided at least one proxy is in use :P) 
Is that what env['action_dispatch.remote_ip'].try(:calculate_ip) doing?

**Comment by giedriusr** [comment]
Sorry, thread is really old, do not use it anymore.
