### ISSUE TITLE
how to restrict Rack::Attack.throttle for specific url or path?

### ISSUE THREAD

**Issue by ved54321** [kickstarter/rack-attack#227]
Hi ,

Can anybody help how can i restrict Rack:Attack:throttle for specific action, like i wanted to block only for API request whose path starts from /api?

I tried doing some modification but still it get applied to all the request. Any help will be great.

**Comment by jogaco** [comment]
From README: throttle all requests to /login and are a post request

```
# Throttle login attempts for a given email parameter to 6 reqs/minute
# Return the email as a discriminator on POST /login requests
Rack::Attack.throttle('logins/email', :limit => 6, :period => 60.seconds) do |req|
  req.params['email'] if req.path == '/login' && req.post?
end
```

Use redis and monitor with redis-cli. You will see what's going on

**Comment by grzuy** [comment]
@ved54321 Were you able to solve this?

**Comment by grzuy** [comment]
Apparently the question has been answered.
Let me know if you want to reopen.
