### ISSUE TITLE
Disable rack-attack throttle to run performance test

### ISSUE THREAD

**Issue by LeoValverde** [kickstarter/rack-attack#228]
I'm creating some specs to validate whether my throttle rules are doing well, however, I want to create another spec right below these ones to evaluate performance. The latter one is written below:

```
    it "performs at least 100 votes per second" do
      expect {
        post "/submit"
      }.to perform_at_least(100).ips
    end
```

Is there some way to temporarily disable rack-attack, only for this specific test?

PS: I've already tried to add the line `Rack::Attack.cache.store.clear` before posting the request, but it returns an error.

**Comment by grzuy** [comment]
> Is there some way to temporarily disable rack-attack, only for this specific test?

You can use `Rack::Attack.enabled = false` for >= 6.2.0.
