### ISSUE TITLE
Long periods expiring prematurely

### ISSUE THREAD

**Issue by SirRawlins** [kickstarter/rack-attack#230]
Afternoon Folks,

I'm trying to use Rack::Attack to throttle on a 'requests per month' basis, using `:period => 1.month` however because of the internal workings which generated a time-based cache key this can result in the cache being expired prematurely, and the requests not being throttled.

**The cache key generation happens like so:**

```ruby
def key_and_expiry(unprefixed_key, period)
	epoch_time = Time.now.to_i
	# Add 1 to expires_in to avoid timing error: http://git.io/i1PHXA
	expires_in = (period - (epoch_time % period) + 1).to_i
	["#{prefix}:#{(epoch_time / period).to_i}:#{unprefixed_key}", expires_in]
end
```

The issue is that for longer periods this can generate inconsistent cache keys, so the key generated on one day of the month may be different than that generated on another.

```
2.3.3 :055 > (Time.parse('Thu, 21 Aug 2017 09:00:00 UTC').to_i / 1.month).to_i
 => 579 
2.3.3 :056 > (Time.parse('Thu, 22 Aug 2017 09:00:00 UTC').to_i / 1.month).to_i
 => 580 
```

I'm looking for any workarounds on this or a little direction on how a PR might look to put something more resilient in place.

Any thoughts and opinions greatly received. And thanks so much for the time invested in this project.

Robert

**Comment by jdelStrother** [comment]
It doesn't align with month boundaries, true, but is that a problem?   The cache key will be 579 from 23rd July -> 21st August, and 580 from 22nd August -> 21st September.

(This might be off-topic for your question, but are you using memcached for your Rack::Attack store?   Our memcached store keeps auto-expiring long lived keys when it runs low on memory, which would also cause problems with long rack-attack periods expiring prematurely)

**Comment by SirRawlins** [comment]
@jdelStrother Thanks for the reply. I see your point regarding the date frame, is that break on the 21st the same for each month? or could it be any arbitrary day?

Good thinking on the Memcached front, but we're using Redis so the store is permanent, and we've plenty of headroom - it's purely the change in cache key which is voiding the cache.

**Comment by jdelStrother** [comment]
AFAICT it drifts away from month-boundaries because 1.month evaluates to 30
days worth of seconds, which obviously isn't always the case.  It'll happen
around the 21st-ish, but it's dependent on how many days were in that month.

**Comment by grzuy** [comment]
Hi @SirRawlins, is this still an issue for you?
Do you think rack-attack still working in an unexpected way?

Thanks

**Comment by SirRawlins** [comment]
@grzuy I can't be sure as I haven't checked in a while. I ended up using [Rack::Throttle](https://github.com/dryruby/rack-throttle) for this use-case instead, and left my existing Rack::Attack stuff in place.

**Comment by grzuy** [comment]
Gotcha.

As @jdelStrother correctly mentioned, you were using `activesupport`s `1.month` which i think returns 1/12 the amount of seconds in a whole year, which is probably never matching the exact amount of seconds in a month.

Thanks for taking the time to report this :-)

**Comment by grzuy** [comment]
If you still consider there's something to be changed, let me know and we reopen.
