### ISSUE TITLE
Is it possible to subscribe only to new throttles?

### ISSUE THREAD

**Issue by brandoncc** [kickstarter/rack-attack#232]
I would like to log when a user is throttled, but not when they make further requests during the same throttle period. How can I achieve that?

Thanks!

**Comment by brandoncc** [comment]
I came up with this and would like input on whether there is a better way, if anybody has a chance:

```ruby
def self.new?(req)
  throttle_name = req.env["rack.attack.matched"]
  discriminator = req.env["rack.attack.match_discriminator"]

  throttle_data = throttle_name.match(/(?<request_count>\d+)in(?<time_period>\d+)seconds/)
  cache_key     = "#{throttle_name}:#{discriminator}"

  period = throttle_data["time_period"].to_i
  limit  = throttle_data["request_count"].to_i

  epoch_time = Time.now.to_i
  # Add 1 to expires_in to avoid timing error: http://git.io/i1PHXA
  expires_in = (period - (epoch_time % period) + 1).to_i
  unprefixed_key = "#{(epoch_time / period).to_i}:#{cache_key}"

  Rack::Attack.cache.read(unprefixed_key) - 1 == limit
end
```

It lives in a domain object I have created for interacting with throttles.

**Comment by marcusmalmberg** [comment]
Bit late to the party, but I tend to do it like:

```
ActiveSupport::Notifications.subscribe("rack.attack") do |name, start, finish, request_id, req|
  request_count = req.env["rack.attack.match_data"][:count]
  limit = req.env['rack.attack.match_data'][:limit]
  
  if request_count == limit + 1
    # First time
  end
end
```

**Comment by brandoncc** [comment]
That is a much cleaner way to do it! I think I will test that in my code and use it instead as long as my tests pass.

**Comment by nadavb** [comment]
@marcusmalmberg, great solution

**Comment by grzuy** [comment]
From what i understand the initial has been answered.
Let me know if you want to reopen.

**Comment by gregblass** [comment]
@marcusmalmberg - The API there seems to have changed, with the last parameter being 'payload'?

I can't seem to get the .env["rack.attack.match_data"][:count] from this no matter what I try.

What's the current way to get that information from within the notifications subscribe block?

**Comment by gregblass** [comment]
OK, I see now that I would just do payload['request'] to get the req object referenced here.

However, I'm not showing anything for `['rack.attack.match_data']`

Is this still passed along in the request in 6.2.2?
