### ISSUE TITLE
Hide deprecation warnings?

### ISSUE THREAD

**Issue by chrishough** [kickstarter/rack-attack#234]
Is there a way to silence...

```
[DEPRECATION] 'Rack::Attack.whitelist' is deprecated.  Please use 'safelist' instead.
[DEPRECATION] 'Rack::Attack.blacklist' is deprecated.  Please use 'blocklist' instead.
```

**Comment by tjnet** [comment]
Replace whitelist with safelist.
Please see here.
https://github.com/kickstarter/rack-attack/blob/8936cc647ac2d310b3cb49fc50fac87486795aff/lib/rack/attack.rb#L28

**Comment by chrishough** [comment]
That was the issue.
