### ISSUE TITLE
On Rails 5.1, using Redis-Cache, find values are expiring years into the future

### ISSUE THREAD

**Issue by maxwell** [kickstarter/rack-attack#235]
We recently upgraded our app to Rails 5.1

previously we had a rule like this, which was working like you'd expect:

```ruby
Rack::Attack.blocklist('Intense Scraping') do |req|
  Rack::Attack::Allow2Ban.filter("intense-:#{req.ip}", :maxretry => 100, :findtime => 1.hour, :bantime => 1.month) do
    req.path.match(%r{hosted_preorders})
  end
end
```

and it was setting the TTL of that count key to be 234898734 hours into the future.

changing it to:

```ruby
Rack::Attack.blocklist('Intense Preorder Scraping') do |req|
  Rack::Attack::Allow2Ban.filter("intense-preorder:#{req.ip}", :maxretry => 100, :findtime => 1.minute.to_i, :bantime => 1.month.to_i) do
    req.path.match(%r{hosted_preorders})
  end
end
```

Made the rule perform as expected again.

Perhaps we should .to_i the expires_in time when sending to redis?

**Comment by maxwell** [comment]
Looks like this is related to Rails 5.1.2

see: https://github.com/rails/rails/issues/29592


closing for now!

Thank you for Rack Attack!

**Comment by maschwenk** [comment]
I feel like this justifies only allowing integer values for this method and throwing a warning if you provide a `ActiveSupport::Duration`. This kind of regression is so risky.
