### ISSUE TITLE
Support for req.remote_ip?

### ISSUE THREAD

**Issue by mapreal19** [kickstarter/rack-attack#236]
I think we need that if we are behind a load balancer.

**Comment by jasonfb** [comment]
@mapreal19 -- this comes from Rack actually (see ```rack-1.5.5/lib/rack/request.rb``` line 348). There's a standard for this, and it should be automatic, but your load balancer needs to set the headers correctly. 

basically, if the header ```REMOTE_ADDR``` exists, it is preferred (used first). If it not, then ```HTTP_X_FORWARDED_FOR``` is used (this is what your router should be doing)

There some more logic in there about guarding against IP spoofing too. 

On Heroku, it Just Works for me. If it is not working for you, I'd check to make sure your load balance is setting the headers correctly as described above.

**Comment by jasonfb** [comment]
see https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by jasonfb** [comment]
Looks like a standard was proposed in [this RFC](https://tools.ietf.org/html/rfc7239), not sure if that option has made it into latest versions of Rack yet or is widely in use.  (I've never seen it as Heroku still uses HTTP_X_FORWARDED_FOR which I think technically is not a standard but is common)

**Comment by mapreal19** [comment]
Thank you @jasonfb for the detailed explanation. Closing this since is related to setting the load balancer correctly
