### ISSUE TITLE
block time

### ISSUE THREAD

**Issue by mm580486** [kickstarter/rack-attack#239]
hi guys
i want show to my users block time 
like instagram api ( for sample after 20 request instagram show me "you are blocked about 1 minute" after refresh instagram show me you are blocked about 30 sec )

**Comment by jasonfb** [comment]
if you want to just show  general message, this is easy. Just make a page in ```public/429.html``` (we use 429 TOO MANY REQUESTS) and configure rack-attack like so:

```
   self.throttled_response = lambda do |env|
     [ 429,  # Too Many Requests
       {},   # headers
       [File.read("#{Rails.root}/public/429.html")]
     ] # body
   end
```

if you want to actually pass the remaining seconds to the page to display to the user, this is more complex and I'm not sure if there's a native way to do that.

**Comment by mm580486** [comment]
i want show to user remain minute of block time !

**Comment by jasonfb** [comment]
OH I see. I don't know how to do that, seems like you'd need to extend or augment this gem.

**Comment by sos4nt** [comment]
Take a look at the example for [X-RateLimit headers for well-behaved clients](https://github.com/kickstarter/rack-attack#x-ratelimit-headers-for-well-behaved-clients):

```ruby
Rack::Attack.throttled_response = lambda do |env|
  now = Time.now
  match_data = env['rack.attack.match_data']

  headers = {
    'X-RateLimit-Limit' => match_data[:limit].to_s,
    'X-RateLimit-Remaining' => '0',
    'X-RateLimit-Reset' => (now + (match_data[:period] - now.to_i % match_data[:period])).to_s
  }

  [ 429, headers, ["Throttled\n"]]
end
```

`match_data[:period] - now.to_i % match_data[:period])` returns the remaining seconds.

**Comment by grzuy** [comment]
Hi @mm580486, is @sos4nt comment what you were looking for?

**Comment by jasonfb** [comment]
@grzuy -- I love this gem it's nice to see maintenance & cleanup on the issues! Surprised more people don't use it, I try to evangelize it everywhere I go.

**Comment by grzuy** [comment]
@mm580486 It sounds like what @sos4nt commented was what you were looking for.

If that not the case let me know and we reopen :-)
Closing for now.

Thanks @sos4nt
