### ISSUE TITLE
Resetting throttle count between tests

### ISSUE THREAD

**Issue by theirishpenguin** [kickstarter/rack-attack#249]
Just wondering, what is the best way to reset the rack attack counters between "it" blocks in a spec, so that throttling can be tested independently in different "it" blocks.

I presume one would use an around block like this...

```
        around(:each) do |each|
            clear_rack_attack_cache
            each.run
            clear_rack_attack_cache
        end
```

Then perhaps...

```
        def clear_rack_attack_cache
            while Rack::Attack.cache.store.instance_variable_get(:@data).keys.length > 0
                Rack::Attack.cache.store.clear
                sleep(1)
            end
        end
```
FYI, using ActiveSupport::Cache::MemoryStore as the backing store. Is a sleep required or is this synchronous?

Either way, it doesn't seem to be working quite right for me as I don't always get the expected number of 200's before I get a 429.

**Comment by markedmondson** [comment]
I'm doing this, it seems to work...

```ruby
    Rack::Attack.throttles.each do |k, throttle|
      Rack::Attack.cache.reset_count("#{k}:#{key}", throttle.period)
    end
```

**Comment by grzuy** [comment]
For the record,

> It appears to me that Rack::Attack.clear! is a bit confusing in that is resetting some things, not everything.

`clear!` has been renamed to `clear_configuration` to avoid further confusion in https://github.com/kickstarter/rack-attack/pull/344.

> think this is something we should add explicit support for, so users don't need to hack the cache store in order to achieve test case isolation in their app tests.

Issue with this goal is the following https://github.com/kickstarter/rack-attack/issues/301

**Comment by grzuy** [comment]
We should consider adding a `Rack::Attack.reset!` method, which should reset all `Rack::Attack`-specific state (mostly throttles, fail2ban and allow2ban counters) so that users can for example do something like:

```rb
config.before do
  Rack::Attack.reset!
end
```

when using RSpec.

**Comment by grzuy** [comment]
> We should consider adding a `Rack::Attack.reset!` method, which should reset all `Rack::Attack`-specific state (mostly throttles, fail2ban and allow2ban counters) so that users can for example do something like:
> 
> ```ruby
> config.before do
>   Rack::Attack.reset!
> end
> ```
> 
> when using RSpec.

`Rack::Attack.reset!` has been implemented and merged in https://github.com/kickstarter/rack-attack/pull/436.
