### ISSUE TITLE
Will throttle work with Elastic Beanstalk?

### ISSUE THREAD

**Issue by bvv218** [kickstarter/rack-attack#251]
I am using elastic beanstalk and I was wondering if rack-attack throttle will be able get users' ip addresses or if all requests will be coming from one ip address because of load balancer?

**Comment by grzuy** [comment]
rack-attack gives you access to a request wrapper object, and it's up to you which value you use to throttle users by.

Whether you can throttle users by client IP is dependent on whether you receive or not the client original IP in the request headers when behind AWS load balancer.

As per AWS docs, seems like you do receive it in `X-Forwarded-For` request header: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for

Have you tried it already?

**Comment by grzuy** [comment]
Hope the above helps :-)
Let me know if it doesn't so we reopen.
