### ISSUE TITLE
How to run Rack::Attack in log only mode

### ISSUE THREAD

**Issue by DanielStevenLewis** [kickstarter/rack-attack#270]
In order to test that I'm not going to accidentally throttle or block legitimate clients, I want to run Rack::Attack in a log-only mode initially. In other words I want to log when Rack::Attack would throttle an IP, but not actually throttle them. How would one do this?

An example scenario that I'm concerned with is a large office building with a whole bunch of people using my app, so that lots of separate, legitimate users appear to have the same IP address. Need to figure out what appropriate limits are for a scenario like this.

**Comment by lmansur** [comment]
The README has a section for this. You are looking for the `#track` method.

https://github.com/kickstarter/rack-attack#tracks

**Comment by grzuy** [comment]
If i understand correctly what @DanielStevenLewis is asking for is to have ability to run rack-attack in "dry-run" mode

**Comment by DanielStevenLewis** [comment]
Guess so. As stated, I want it to only log (without blocking or
throttling), so I can see what would happen if blocking or throttling was
to be enabled. Do tracks not actually provide this functionality?

On Mar 8, 2018 3:09 PM, "Gonzalo Rodriguez" <notifications@github.com>
wrote:

If i understand correctly what @DanielStevenLewis
<https://github.com/danielstevenlewis> is asking for is to have ability to
run rack-attack in "dry-run" mode

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kickstarter/rack-attack/issues/270#issuecomment-371608858>,
or mute the thread

**Comment by lmansur** [comment]
I see `.track` as exactly what you need. In fact, that's what we used before actually throttling the clients.

**Comment by DanielStevenLewis** [comment]
Great!

**Comment by DanielStevenLewis** [comment]
Thank you

**Comment by grzuy** [comment]
Closing for now then :-)
If that doesn't work for you we can reopen later.
