### ISSUE TITLE
Proposal to go back to CHANGELOG.md

### ISSUE THREAD

**Issue by lmansur** [kickstarter/rack-attack#288]
In e5cf56ae462a5c97f674b64491f91bdfc7f7a3ed it was decided to stop using `CHANGELOG.md` in favor of documenting changes in GitHub releases.

Most Open Source projects use a file in the project root to document their changes. The change to the releases wasn't documented so I'm not sure what was the reason behind it, but I think we should revert back to `CHANGELOG.md`.

A user looking for the history of changes most likely will open `CHANGELOG.md` before checking the release page. Depending on his hurry, he will miss entirely the warning that says we moved to GH Releases and assume the last release was `v5.0.0.beta1`. If he notices the link to Releases, he now has one more click to reach his desired destination.

Moreover, the current format makes it impossible to read the updated change log locally, forcing the reader to visit GitHub.

In 2014, Olivier Lacan started the [Keep a Changelog](http://keepachangelog.com/) project. I think we should adhere to it moving forward. This helps the community as whole by sticking to a well-designed convention.

Should the maintainers accept this proposal, I'm happy to port back all changes from the Releases page to the `CHANGELOG.md` file and format it according to the convention.

**Comment by grzuy** [comment]
Hi @lmansur,

> Should the maintainers accept this proposal, I'm happy to port back all changes from the Releases page to the CHANGELOG.md file and format it according to the convention.

I like it.
If you want to work on this, can you first just backport the missing pieces to the `CHANGELOG.md` without changing the format?
Format convention sounds like a separate discussion.

Thanks for the proposal!

**Comment by lmansur** [comment]
Sure thing, @grzuy. I'll work on it
