### ISSUE TITLE
rack_attack_cache_spec.rb test case fails occasionally in CI builds

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#292]
Last two instances i saw a jruby CI build job fail was with a test case from `spec/integration/rack_attack_cache_spec.rb`

**Comment by grzuy** [comment]
Failed again: https://travis-ci.org/kickstarter/rack-attack/builds/352967658

**Comment by grzuy** [comment]
Seems unrelated to jruby.
Job failed for ruby 2.5.0 also.

The common pattern is that, when it fails, it does always for one of the test cases from `spec/integration/rack_attack_cache_spec.rb`

**Comment by lmansur** [comment]
I've seen it fail in the CI for `Rack::Attack::StoreProxy::DalliProxy` and `ActiveSupport::Cache::DalliStore`.
Locally I consistently get 12 failures for `Rack::Attack::StoreProxy::RedisStoreProxy`. Very intriguing.

**Comment by lmansur** [comment]
`RedisStoreProxy` - and all other proxies - have exception supression in all their methods. I decided to remove the empty rescue from the `RedisStoreProxy` methods and started receiving a new kind of failure:

```
Error:
Rack::Attack::Cache::with Rack::Attack::StoreProxy::RedisStoreProxy::reset_count#test_0001_must delete the value:
Redis::CommandError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

A quick [Google search](https://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots) led me to disable the snapshot save attempt by executing the following in the `redis-cli`:

`
config set stop-writes-on-bgsave-error no
`

Now all my tests are green. I'm not really sure what to make of it, but it's a start.

**Comment by grzuy** [comment]
This test file was removed/replaced in the following PR https://github.com/kickstarter/rack-attack/pull/360.

Closing...
