### ISSUE TITLE
Proposal regarding CHANGELOG.md formatting

### ISSUE THREAD

**Issue by lmansur** [kickstarter/rack-attack#295]
As a continuation of #288, I propose we set some formatting conventions for our CHANGELOG.

Reinforcing what I said before, we should follow the conventions suggested by the [Keep a Changelog](https://keepachangelog.com) project. This means:

- There should be an entry for every version
- The same types of changes should be grouped
- Versions and sections should be linkable.
- The latest version comes first.
- The release date of each version is displayed.
- Mention whether you follow Semantic Versioning.
- Keep an `Unreleased` section at the top to track upcoming changes.

What they call "types of changes":

- `Added` for new features.
- `Changed` for changes in existing functionality.
- `Deprecated` for soon-to-be-removed features.
- `Removed` for now removed features.
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

Version headers should follow the following format:

```markdown
## [1.0.0] - 2018-03-13
```

The date format follows the order of largest to smallest units, so `year`, `month` and `day`. This conforms with [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html).

The version number is between `[brackets]` so GitHub automatically links it to a diff between this version and the previous latest version. The same is true for `Unreleased`, so GitHub links the diff of HEAD and latest version.

Should this proposal be approved, I'll format our current changelog accordingly.

**Comment by grzuy** [comment]
Hi @lmansur, thanks for the proposal.

I do like the idea.

Can we start small and only change the following for now?

* Adjust version dates in titles to the proposed format
* Make version linkable in titles
* Make issues and pull requests mentioned linkable
* Add an empty "Unreleased" section

**Comment by lmansur** [comment]
Sounds good :+1:

**Comment by lmansur** [comment]
@grzuy Correcting what I said on the issue:

> The version number is between [brackets] so GitHub automatically links it to a diff between this version and the previous latest version. The same is true for Unreleased, so GitHub links the diff of HEAD and latest version.

This is **not** done automatically by GitHub. We still need to add a reference. So it would actually be:

```markdown
## [5.0.1] - 2016-08-11
```

and at the end of the file:
```markdown
[5.0.1]: https://github.com/kickstarter/rack-attack/compare/v5.0.0...v5.0.1/ 
```

**Comment by grzuy** [comment]
> What they call "types of changes":
>    * `Added` for new features.
>    * `Changed` for changes in existing functionality.
>    * `Deprecated` for soon-to-be-removed features.
>    * `Removed` for now removed features.
>    * `Fixed` for any bug fixes.
>    * `Security` in case of vulnerabilities.

This sounds useful.

Let's start using it for upcoming releases for now. If it ends up being useful for us and users, we can later consider categorizing old releases.

**Comment by grzuy** [comment]
Thanks again Lucas!
