### ISSUE TITLE
Stick to a ruby style guide

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#302]
As rack-attack gem developers
We want to stick to a ruby code style guide
So that codebase is consistent and there's less decisions to be made about code style when coding

Idea brought up by @lmansur in https://github.com/kickstarter/rack-attack/pull/284

**Comment by grzuy** [comment]
I think it would be great code style checks to be part of the regular workflow. So that e.g. anyone cloning the repo could easily check code style. I.e.

* Contributor clones rack-attack repo
* `$ bundle install`
* `$ rake` runs tests + rubocop, and is all green
* Contributor codes something in a topic branch
* `$ rake` to check tests and rubocop again

**Comment by grzuy** [comment]
A possible way to start small on this could be adding rubocop and running `$ rubocop --auto-gen-config`, which leaves you with no offenses and a TODO list of offenses to work-on/fix. Then we can tackle each offense one by one, instead of trying to fix them all at once.

**Comment by lmansur** [comment]
Are we going to stick to the default configuration?

**Comment by grzuy** [comment]
Hi @lmansur, good question. Not sure.

Can we start with something like this for now?

```
AllCops:
  DisabledByDefault: true

Layout:
  Enabled: true
```

We fix all layout offenses.
We grow from there.

**Comment by grzuy** [comment]
PR welcomed if you want to work on that first step :-)
Let me know.

**Comment by lmansur** [comment]
I think the config you posted is good. 

We should be careful when incorporating Rubocop into the contribution workflow. I think we ought to point Rubocop as an important tool to reaching a consistent codebase but leaving very explicit that the Cops are a guiding point and not set in stone.

There are some Cops that I personally disagree with (and so does a good share of the community), so we should have an open space for the discussion of what we think is valid or not.

With that in mind, I'm happy to work on a PR. What do you need for the first step? Generate the mentioned configuration file, fix the layout offenses and update the contribution workflow?

**Comment by grzuy** [comment]
> With that in mind, I'm happy to work on a PR.

Thank you!

> What do you need for the first step? Generate the mentioned configuration file, fix the layout offenses and update the contribution workflow?

Yes, please.

**Comment by grzuy** [comment]
@lmansur Anything i can do to help with this let me know

**Comment by lmansur** [comment]
I didn't have the time yet to start the PR. I'll try and get it over with this week

**Comment by grzuy** [comment]
Sure, no worries. Just checking in case i could help in any way.

Thanks again!
