### ISSUE TITLE
whitelist not work

### ISSUE THREAD

**Issue by shatle** [kickstarter/rack-attack#32]
In Rails4

```
# in Gemfile
gem 'rack-attack'
```

```
# In config/application.rb
config.middleware.use Rack::Attack
```

```
# In config/initializers/rack_attack.rb
Rack::Attack.whitelist('allow from localhost') do |req|
  # Requests are allowed if the return value is truthy
  Rails.logger.debug "................"
  Rails.logger.debug "req.id:   #{req.ip} : #{'127.0.0.1' == req.ip} "
  Rails.logger.debug "................"
  '127.0.0.1' == req.ip
end
```

when i request a json data , likes `/posts.json`.  The log output:

```
Started GET "/posts.json" for 192.168.1.101 at 2013-09-10 17:24:33 +0800
................
req.id:   192.168.1.101 : false 
................
Processing by PostsController#index as JSON
```

it return json data successfully. WHY??

`192.168.1.101` is not localhost

The Rack::Attack.whitelist return `false` and Controller is still  fired?

Can I set something, which does not fire controller, or return incorrect json data? And How?

**Comment by 34code** [comment]
Took me a while to understand the same thing.. good thing I googled "rack attack whitelist not working" and came here :smile: .. of course whitelist WAS actually working as advertised.
