### ISSUE TITLE
Compute IP address just once?

### ISSUE THREAD

**Issue by david-a-wheeler** [kickstarter/rack-attack#345]
In a system I manage, computing the client IP address takes several steps, and I have several Rack::Attack patterns based on IP address.  Is there a way to calculate a client IP address just once, and then reuse it multiple times?  I'm guessing there is, in which case it'd be nice to see it documented...!

**Comment by grzuy** [comment]
Hi,

You can open `Rack::Attack::Request` class and define new methods. See https://github.com/kickstarter/rack-attack/wiki/Advanced-Configuration#rackattackrequest-helpers.

A pull request adding this type of documentation to the README is very welcomed :-)
