### ISSUE TITLE
No response with throttling

### ISSUE THREAD

**Issue by ayham95** [kickstarter/rack-attack#346]
It works fine, But the server doesnt respond at all to the request. All i got is : 
`Started POST "/like" for 127.0.0.1 at 2018-06-16 03:51:23 +0300` then it hangs.

**Comment by lmansur** [comment]
Can you provide an app that reproduces this issue? If not, could you post your `Gemfile.lock` and the rack-attack configuration? What kind of cache store are you using? Maybe the connection to the cache is hanging?
