### ISSUE TITLE
Redis gem required even if not using Redis cache store

### ISSUE THREAD

**Issue by maurosbu** [kickstarter/rack-attack#355]
The Redis cache store requires the redis gem, version 4.0.1 or later. Please add it to your Gemfile: `gem "redis", "~> 4.0"`
     /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': redis is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
     
     
     /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem'
     activesupport (5.2.0) lib/active_support/cache/redis_cache_store.rb:4:in `<top (required)>'
     activesupport (5.2.0) lib/active_support/dependencies.rb:283:in `require'
     activesupport (5.2.0) lib/active_support/dependencies.rb:283:in `block in require'
     activesupport (5.2.0) lib/active_support/dependencies.rb:249:in `load_dependency'
     activesupport (5.2.0) lib/active_support/dependencies.rb:283:in `require'
     rack-attack (5.3.1) lib/rack/attack/store_proxy/redis_cache_store_proxy.rb:8:in `handle?'
     rack-attack (5.3.1) lib/rack/attack/store_proxy.rb:11:in `block in build'
     rack-attack (5.3.1) lib/rack/attack/store_proxy.rb:11:in `each'
     rack-attack (5.3.1) lib/rack/attack/store_proxy.rb:11:in `find'
     rack-attack (5.3.1) lib/rack/attack/store_proxy.rb:11:in `build'
     rack-attack (5.3.1) lib/rack/attack/cache.rb:13:in `store='
     rack-attack (5.3.1) lib/rack/attack/cache.rb:7:in `initialize'
     rack-attack (5.3.1) lib/rack/attack.rb:121:in `new'
     rack-attack (5.3.1) lib/rack/attack.rb:121:in `cache'
     rack-attack (5.3.1) lib/rack/attack/throttle.rb:18:in `cache'
     rack-attack (5.3.1) lib/rack/attack/throttle.rb:28:in `[]'
     rack-attack (5.3.1) lib/rack/attack.rb:106:in `block in throttled?'
     rack-attack (5.3.1) lib/rack/attack.rb:105:in `any?'
     rack-attack (5.3.1) lib/rack/attack.rb:105:in `throttled?'
     rack-attack (5.3.1) lib/rack/attack.rb:176:in `call'
     rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
     rack (2.0.5) lib/rack/etag.rb:25:in `call'
     rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
     rack (2.0.5) lib/rack/head.rb:12:in `call'
     actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
     rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
     rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
     activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
     activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
     actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
     rack-contrib (2.0.1) lib/rack/contrib/response_headers.rb:17:in `call'
     meta_request (0.6.0) lib/meta_request/middlewares/headers.rb:16:in `call'
     web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
     web-console (3.6.2) lib/web_console/middleware.rb:22:in `block in call'
     web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
     web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
     railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
     railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
     activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
     activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
     activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
     railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
     sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
     request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
     rack (2.0.5) lib/rack/method_override.rb:22:in `call'
     rack (2.0.5) lib/rack/runtime.rb:22:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
     rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
     actionpack (5.2.0) lib/action_dispatch/middleware/ssl.rb:74:in `call'
     railties (5.2.0) lib/rails/engine.rb:524:in `call'
     /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
     This error occurred while loading the following files:
        active_support/cache/redis_cache_store

**Comment by grzuy** [comment]
Hi @maurosbu, thanks for the issue report!

Are you setting `Rack::Attack.cache.strore`?
Which is rails `cache_store` set to?

**Comment by maurosbu** [comment]
@grzuy thanks for the reply.
I'm not setting `Rack::Attack.cache.store`, therefore, as said in the doc, it defaults to Rails.cache.

    2.5.1 :001> Rails.configuration.cache_store
     => :memory_store

This is the default for development environment (if cache is enabled).

**Comment by grzuy** [comment]
Gotcha, I can also reproduce on my side when `Rails.cache` is set to `:memory_store`.

Apart from fixing the issue, we'll need to refactor test suite in some way `redis` (and probably other optional deps) are not always required for all test examples. So we can catch this kind of issues in the future.

Thanks again!

**Comment by maurosbu** [comment]
@grzuy I'll try the new version and give a feedback, once released.

**Comment by grzuy** [comment]
`5.3.2` is out

**Comment by CvX** [comment]
The issue is still present in 5.4.0 when using Redis 3.x, `Rails.configuration.cache_store` is a NullStore and `Rack::Attack.cache.store` isn't configured.

**Comment by grzuy** [comment]
Good catch, thank you!

**Comment by grzuy** [comment]
`5.4.2` is out
