### ISSUE TITLE
Inconsistent prefixing of cache key

### ISSUE THREAD

**Issue by morgoth** [kickstarter/rack-attack#370]
I'm using Rails cache (with default Redis wrapper available in Rails 5.2)
I configured rack attack to use custom prefix `Rack::Attack.cache.prefix = "rate-limit"`
Rails cache is having prefix `rc`
```ruby
config.cache_store = :redis_cache_store, {
   url: "my-redis-url",
   expires_in: 1.hour.to_i,
   namespace: "rc"
}
```

I noticed cache keys:
`rate-limit:25501675:allow2ban:count:ip`, but actuall ban is written to `rc:rate-limit:allow2ban:ban:ip` which is inconsistent.

Going deeper:
```
> Rack::Attack.cache.store.write('yo', 1)
=> "OK"
> Rack::Attack.cache.store.increment('nope', 1)
=> 1
> Redis.current.keys
=> ["rc:yo", "nope"]
```

**Comment by grzuy** [comment]
Hi @morgoth,

Thanks for reporting!

Which version of:
- rails
- redis
- rack-attack

are you using?

**Comment by morgoth** [comment]
It's:
* Rails 5.2.0
* Redis 2.8.23
* rack-attack 5.4.0

**Comment by lmansur** [comment]
@morgoth which version of the Redis gem are you using? I couldn't find this version for the gem, so I guess that's the server version.

**Comment by lmansur** [comment]
@morgoth Could you also post your initializer? I couldn't reproduce this problem running Rails 5.2, Redis (gem) 4.0.1 and rack-attack 5.4.0. All my keys were correctly prefixed.

`Rack::Attack.cache.store` is currently meant to be used internally by `Rack::Attack.cache`, not externally. `Rack::Attack.cache` already prefixes (with `Rack::Attack.prefix`) all keys supplied to it, so `store` doesn't care about that.

The only prefix you will see when using `Rack::Attack.cache.store` directly is the namespace supplied in the Redis configuration, since this is handled internally by Redis.

**Comment by morgoth** [comment]
Yes, it was a Redis server, redis gem has version 4.0.1
Sample initializer:

```ruby
Rack::Attack.cache.prefix = "rate-limit"

Rack::Attack.throttle("auth", limit: 5, period: 20.seconds) do |request|
  request.env["action_dispatch.remote_ip"]
end

Rack::Attack.blocklist("allow2ban registration login scrappers") do |req|
  ip = req.env["action_dispatch.remote_ip"]
  Rack::Attack::Allow2Ban.filter(ip, maxretry: 50, findtime: 1.minute, bantime: 1.hour) do
    true
  end
end
```

**Comment by lmansur** [comment]
I'm having a little trouble reproducing your problem. My initializer is the sample you provided:

```ruby
# config/initializers/rack_attack.rb

Rack::Attack.cache.prefix = "rate-limit"

Rack::Attack.throttle("auth", limit: 5, period: 20.seconds) do |request|
  request.env["action_dispatch.remote_ip"]
end

Rack::Attack.blocklist("allow2ban registration login scrappers") do |req|
  ip = req.env["action_dispatch.remote_ip"]
  Rack::Attack::Allow2Ban.filter(ip, maxretry: 50, findtime: 1.minute, bantime: 1.hour) do
    true
  end
end
```

My Redis configuration:
```ruby
config.cache_store = :redis_cache_store, {
      expires_in: 1.hour.to_i,
      namespace: 'rc'
    }
```

Versions:
Ruby 2.5.1
Rails 5.2.0
Redis 4.0.1
Rack-Attack 5.4.0

My Redis keys started empty. After 6 requests, they looked like this:
```ruby
[
  "rc:rate-limit:76697590:auth:127.0.0.1",
  "rc:rate-limit:25565863:allow2ban:count:127.0.0.1"
]
```

I deleted the previous keys and made 51 requests, they looked like this:
```ruby
[
  "rc:rate-limit:25565864:allow2ban:count:127.0.0.1", 
  "rc:rate-limit:allow2ban:ban:127.0.0.1",
  "rc:rate-limit:76697594:auth:127.0.0.1"
]
```

All keys are correctly prefixed, as expected.

Is this the actual initializer you are using? Are you by any chance calling `Rack::Attack.cache.store` directly and using their interface?

Thank you for the follow up.

**Comment by morgoth** [comment]
I cannot reproduce it again. Tried with new app and with the old one where I encountered it.
Even this is now consistent:
```
[8] pry(main)> Rack::Attack.cache.store.write('yo', 1)
=> "OK"
[9] pry(main)> Rack::Attack.cache.store.increment('nope', 1) 
=> 1
[10] pry(main)> Redis.current.keys
=> ["rc:yo", "rc:nope"]
```
Not sure what happened...
Sorry for taking your time.
