### ISSUE TITLE
LOGO PROPOSAL FOR Rack-attack

### ISSUE THREAD

**Issue by orlant** [kickstarter/rack-attack#375]
Hello I am a graphic designer and I like to make contributions in open source projects, if you allow me I can create a logo for your repository?

**Comment by grzuy** [comment]
Hi @orlant,

I'll leave that decision to an owner, cc @frewsxcv.

Thank you for your interest!

**Comment by frewsxcv** [comment]
Thanks for the offer @orlant! We really appreciate you reaching out, but we're not looking for a logo for this project at this time. Maybe in the future though!
