### ISSUE TITLE
Remaining period to next successful API call for a throttled request.

### ISSUE THREAD

**Issue by imi56** [kickstarter/rack-attack#379]
Currently, I don't find any information about after how much time the user can make a successful API call. 
Use case: I want to limit user **3 API calls per 60 mins**. If the **user exceeds the limit** "Please retry after 60 mins" message is displayed which is a hardcoded message. Now if the user **retires after 55 minutes** he gets the same message("Please retry after 60 mins") which is wrong because now the message should be "Please retry after 5 mins". How can I get this **remaining 5 min duration**? 
Note: I am not storing any data in the DB for API calls simply because its a get request.
The matched data is:
```
env['rack.attack.match_data'] >>
{
     :count => 6,
    :period => 3600,
     :limit => 3
}
```

**Comment by lmansur** [comment]
You closed the issue, so I guess you figured it out. For those with the same question, there was a discussion regarding the Retry-After response in [this issue](https://github.com/kickstarter/rack-attack/issues/209).

However, you don't have to wait for someone to implement the change. The README documents how you can set headers for well-behaved clients [here](https://github.com/kickstarter/rack-attack/issues/379)
