### ISSUE TITLE
Can't use blocklist_ip

### ISSUE THREAD

**Issue by Beengie** [kickstarter/rack-attack#383]
I am getting an error 'undefined method `blocklist_ip' for Rack::Attack:Class' when I put the following in rack_attack.rb. 

Rack::Attack.blocklist_ip("79.110.25.224")
Rack::Attack.blocklist_ip("94.25.169.98")

I have looked for help and I am unsuccessful finding any. I saw some things about the cache but I don't understand with the documentation that I have seen.

**Comment by lmansur** [comment]
The shorthand methods (such as `#blocklist_ip`) were added in rack-attack 5.2.0. What version are you using?

**Comment by Beengie** [comment]
Thanks for getting back to me. I am using 5.0.1. I tried using the shorthand.. 

class Rack::Attack
   Rack::Attack.blocklist_ip("79.110.25.224")
   Rack::Attack.blocklist_ip("94.25.169.98")
...
end

I get the error `undefined method "blocklist_ip" for Rack::Attack:Class`. 
When I change it to `blocklist("79.110.25.224")` there is no error. 
Is this the proper usage without the "_ip"?

**Comment by Beengie** [comment]
I upgraded to 5.4.0... 
Thanks for the help. It is working now.

**Comment by grzuy** [comment]
Cool.

Thank you @lmansur and @Beengie!
