### ISSUE TITLE
How to clear the cache of the Rack Attack only

### ISSUE THREAD

**Issue by ndvbd** [kickstarter/rack-attack#389]
How to clear the cache of the Rack Attack only?  (clear state)
One way would be to simply change the cache prefix of the rack attack. How do we do that?

**Comment by grzuy** [comment]
There's not an easy way to do that currently.

We should add that as a new feature.

**Comment by nadavb** [comment]
How can I change the cache prefix for the rack attack? It should be somewhere, shouldn't it? If I change the prefix, it will solve the problem, as it will invalidate the relevant cache entries.

**Comment by grzuy** [comment]
Yes, changing the prefix would kind of workaround to start with a clean state.

```ruby
Rack::Attack.cache.prefix = ... # default is 'rack::attack'
```

We should aim to provide a clean way to clean all the data without needed to hack the cache prefix anyway.

**Comment by grzuy** [comment]
@ndvbd Just curious, what was your motivation for clearing the cache? Were you needing that during test cases so to achieve proper test case isolation or was that a need for you on production?

**Comment by grzuy** [comment]
We should consider having a `Rack::Attack.reset!` method to reset all Rack::Attack's state (i.e. the cache).

Also discussed in https://github.com/kickstarter/rack-attack/issues/249#issuecomment-539029878.

**Comment by ndvbd** [comment]
@grzuy Yes. You sometimes need to clean the cache, especially during tests, but also on production. It's a good thing to have.

**Comment by lmansur** [comment]
@ndvbd what is your context on cleaning the cache on production? It's not something I see very often, so I'm just curious

**Comment by javierjulio** [comment]
For others that need this currently in their test suite, this is what we use in our RackAttack specific test cases:

```ruby
  before do
    Rack::Attack.enabled = true
    Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new
  end

  after do
    Rack::Attack.cache.store.clear
    Rack::Attack.enabled = false
  end
```

Note that this makes use of the new `enabled` flag in RackAttack 6.2.0.

I like the suggestion of `Rack::Attack.reset!` or even another solution. Perhaps a method specific to clearing the cache or a test mode flag as suggested in #436.

**Comment by grzuy** [comment]
> For others that need this currently in their test suite, this is what we use in our RackAttack specific test cases:
> 
> ```ruby
>   before do
>     Rack::Attack.enabled = true
>     Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new
>   end
> 
>   after do
>     Rack::Attack.cache.store.clear
>     Rack::Attack.enabled = false
>   end
> ```
> 
> Note that this makes use of the new `enabled` flag in RackAttack 6.2.0.
> 
> I like the suggestion of `Rack::Attack.reset!` or even another solution. Perhaps a method specific to clearing the cache or a test mode flag as suggested in #436.


Hi @javierjulio , 

Going through this again, I am not sure we'll have something in Rack::Attack which will avoid you having to make an extra call to clear the storage.

I mean, you either:
1. Have Rack::Attack completely disabled for tests, via `enabled = false` or by using `NullStore` (`config.cache = :null_store` in rails).
2. Have Rack::Attack enabled for tests and some sort of reset state call (today `Rack::Attack.cache.store.clear`) somewhere in between test cases.

Were you expecting something different in that regard?
If so, what specifically?

Thanks.

**Comment by grzuy** [comment]
`Rack::Attack.reset!` has been merged in https://github.com/kickstarter/rack-attack/pull/436.
