### ISSUE TITLE
Safelist still allowing all traffic

### ISSUE THREAD

**Issue by harmoney-jianbo** [kickstarter/rack-attack#390]
Hi,  Please correct me if Im wrong. When I defined safe list as follows, will it only allow incoming traffic from IP 5.6.7.8, and all other IP will be blocked? it seem to still allowing all traffic through. 

Rack::Attack.safelist_ip("5.6.7.8")

**Comment by lmansur** [comment]
No, safelisting an IP will make sure this IP is never blocked. It has no effect on other IPs

**Comment by grzuy** [comment]
Thank you for your answer

**Comment by harmoney-jianbo** [comment]
Thank you
