### ISSUE TITLE
Mixed-case value for discriminator problem

### ISSUE THREAD

**Issue by sidonath** [kickstarter/rack-attack#395]
I've recently implemented throttling with Rack::Attack and figured that the login throttling could be circumvented by switching the case of a case-insensitive email. I resolved the problem by returning a downcased value from the discriminator block.

I believe Rack::Attack should treat discriminator as a case-insensitive value by default, while providing an option to disable the behavior conditionally.

Any thoughts on this? I'd be willing to submit a PR with the change.

**Comment by grzuy** [comment]
Interesting.

Yes. Probably safer defaulting to case-insensitive while providing the config option to disable.

PR welcome.
Thank you @sidonath.

**Comment by lmansur** [comment]
The discriminator is something the user explicitly defines the way he sees fit. As a user of the gem, I would find the interface more complex than it needs to be if I have to account for internal manipulations of the discriminator by the gem and configure it accordingly. 

However, I think this idea does have its merits. I propose two alternate solutions:

**1:**
Downcase the discriminator **only** if the user enables it in the configuration. This is not a breaking change and avoids hidden behavior. For those that find this relevant, they can easily activate it.

**2:**
This is a more complex solution, but also more flexible. By default, `rack-attack` does not manipulate your discriminator. However, the user can provide the gem with chainable methods that will be called by the discriminator. For example:

```ruby
Rack::Attack.filters = [:downcase, :strip, :chomp]
# or
Rack::Attack.filters = [:to_i]
```

This solves the case problem and also many other possible issues, such as using whitespace to fool the counter.

What do you think @sidonath @grzuy ?

**Comment by grzuy** [comment]
I think the decision here is whether to make discriminator matching case insensitive or not.

If we decide we don't then I would be hesitant to add an extra configuration to enable it, because you could do that in your throttle block by downcasing already. Config option would make sense to disable it, if we add it, because that would be the only way to override it.

**Comment by grzuy** [comment]
> As a user of the gem, I would find the interface more complex than it needs to be if I have to account for internal manipulations of the discriminator by the gem and configure it accordingly.

Do you have any specific discriminator examples for which you'd be worried case-insensitive matching would become problematic or unexpected/surprising for users?

**Comment by lmansur** [comment]
I think you are both right, I may have over thought the issue.
