### ISSUE TITLE
Make blocklisted response load a custom error page

### ISSUE THREAD

**Issue by weiyunlu** [kickstarter/rack-attack#396]
Hi,

I would like to have Rack::Attack load a custom error page instead of the default text "Forbidden".  I have discovered that I can do this by literally pasting the entire HTML content of the error page I wish to load into the third argument like so:

`Rack::Attack.blocklisted_response = lambda do |env| 
[ 403, { 'Content-Type' => 'text/html' }, ['<!DOCTYPE html> (entire custom error page code here)... ']] `

but is there an elegant way to ask it to simply load the page from, say, `public/403.html`?

**Comment by lmansur** [comment]
https://stackoverflow.com/questions/36224977/rails-rendering-html-from-rack

I haven't tried this before, but the question above is a starting point

**Comment by weiyunlu** [comment]
This worked.  Thank you!
