### ISSUE TITLE
Add a Rack::Attack.create_request 

### ISSUE THREAD

**Issue by philss** [kickstarter/rack-attack#399]
## What

This is a feature request that enables clients to add a handler to transform the `request` into an object that quacks like we want. It is something like this:

```ruby
Rack::Attack.create_request = -> (env) { ActionDispatch::Request.new(env) }
```

This would be configured inside an initializer script.

## Why

This feature request would avoid the problem of working with `JSON` requests in Rails. Today `Rack::Attack` does not work smoothly when you need to fetch a parameter from a JSON endpoint in Rails. This leads to blocks configured like this:

```ruby
Rack::Attack.throttle('my limit', limit: limit, period: period) do |req|
  if req.path == '/api/v1/my-endpoint' && req.post?
    real_req = ActionDispatch::Request.new(req.env)
    real_req.params['email']
  end
end
```

## Related issues

I found this issue to be related to it: https://github.com/kickstarter/rack-attack/issues/122

This was an idea gave by @lucasmazza in a private repo.

**Comment by lmansur** [comment]
What about monkey patching the request object, as exemplified here (https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack/request.rb)?

**Comment by philss** [comment]
I wish I could avoid monkey patching. But how would be the implementation?
Something like this?

```ruby
module Rack
  class Attack
    class Request
      def params(*args)
        ActionDispatch::Request.new(env).params(*args)
      end
    end
  end
end
```

**Comment by lmansur** [comment]
That should work.

**Comment by philss** [comment]
Thanks, @lmansur. I'm going to stick with the original version version of creating a new object and move to the monkey patch version if the problem grows.
