### ISSUE TITLE
Throttle Basic Auth Crackers doc

### ISSUE THREAD

**Issue by parasharrk** [kickstarter/rack-attack#413]
Advance conf doc https://github.com/kickstarter/rack-attack/blob/master/docs/advanced_configuration.md#throttle-basic-auth-crackers

As this code comments says "# Return true if the authorization header not incorrect"
and this block is working like "# Return true if the authorization header is incorrect"

Just wanted to understand this block!

**Comment by grzuy** [comment]
Good find, thank you!

Fixed in https://github.com/kickstarter/rack-attack/commit/306d157df340aeea1229af08c79ad57a8c847481
