### ISSUE TITLE
Changelog for 6.1.0?

### ISSUE THREAD

**Issue by woodhull** [kickstarter/rack-attack#424]
Rubygems thinks 6.1.0 has been released, but there is nothing in the Changelog for it. What's included?

https://rubygems.org/gems/rack-attack/versions/6.1.0

**Comment by javierjulio** [comment]
This would be helpful to have. 🙏🏻 We received an update from Dependabot but no changelog was included.

**Comment by grzuy** [comment]
Sorry about that.
Will update asap.

In the meantime, you can look at this to see the changes between versions https://github.com/kickstarter/rack-attack/compare/v6.0.0...v6.1.0/.

**Comment by javierjulio** [comment]
@grzuy no problem, thanks! ❤️
