### ISSUE TITLE
Auto plug middleware for simpler installation

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#429]
So we can remove this step https://github.com/kickstarter/rack-attack#plugging-into-the-application, at least for Rails apps can be achieved by defining a rack-attack railtie.

https://api.rubyonrails.org/classes/Rails/Railtie.html

**Comment by grzuy** [comment]
Need to be careful of not inserting the middleware a second time, when the user has already inserted middleware in `config/application.rb` or elsewhere.

**Comment by lmansur** [comment]
@grzuy do you have any suggestions on how to ensure we don't include the middleware more than once?

We can make use of Rails's private API:

```ruby
module Rack
  class Attack
    class Railtie < Rails::Railtie
      initializer "railtie.configure_rails_initialization" do |app|
        include_middleware = app.middleware.send(:operations).none? do |operation|
          middlewares = operation[1]
          middlewares.include?(Rack::Attack)
        end
        app.middleware.use Rack::Attack if include_middleware
      end
    end
  end
end
```

I'm not really a fan of using their private API, but I don't see any other way to achieve this.

**Comment by grzuy** [comment]
Hi @lmansur,

I briefly looked into this when I first wrote the issue and didn't see any obvious easy way to know if a middleware was already inserted.

**Comment by grzuy** [comment]
Also, given that those are "operations" to the middleware stack they could potentially be removals of `Rack::Attack`, right?

**Comment by lmansur** [comment]
`#operations` will only return non-delete operations. The deletes are in `#delete_operations`.

https://github.com/rails/rails/blob/master/railties/lib/rails/configuration.rb#L61-L63

**Comment by grzuy** [comment]
Can happen that `Rack::Attack` middleware is both in `operations` and `delete_operations`?

**Comment by lmansur** [comment]
It can.

If the user sets `app.middleware.delete Rack::Attack` this operation will be added to `delete_operations`. If the user also sets `app.middleware.use Rack::Attack` (or `app.middleware.insert_after/insert_before/swap`) or we set it for him, there will be an inclusion operation in `operations` and a delete operation in `delete_operations`. In this case, the middleware won't be used.

**Comment by grzuy** [comment]
Gotcha. Sounds good then. We are fine only checking the `operations` I guess.

**Comment by fatkodima** [comment]
I'm wondering, if this worth it? As i noticed, many (most?) applications use it only for production/staging.
For me, as a user, it's much easier and clear to explicitly enable it where i want than to disable otherwise.

**Comment by grzuy** [comment]
Hi @fatkodima,

Fair concern.

If moving forward with this we will need a configurable `enabled` boolean.
I think that would help with cases like https://github.com/kickstarter/rack-attack/issues/220 and https://github.com/kickstarter/rack-attack/issues/384. Flipping an `enabled` boolean might be easier and more intuitive than plugging/unplugging middleware.

**Comment by grzuy** [comment]
> Need to be careful of not inserting the middleware a second time, when the user has already inserted middleware in `config/application.rb` or elsewhere.

Maybe we should also make Rack::Attack idempotent. I.e. Doesn't matter if the middleware gets accidentally added more than once.
