### ISSUE TITLE
[meta] 2FA for gem pushers

### ISSUE THREAD

**Issue by lmansur** [kickstarter/rack-attack#430]
The RubyGems account of one of the maintainers of `rest-client` was breached, enabling the attacker to push code with a backdoor. (details here: https://github.com/rest-client/rest-client/issues/713)

That's not the first time this kind of breach has happened.

Since there's no way of knowing if the authors of a given gem actually use 2FA, I'm opening this issue so we can keep an open discussion regarding this.

As a user of this gem, I would feel a lot safer if everyone with push rights had 2FA enabled.

Thanks!

**Comment by grzuy** [comment]
Hi @lmansur,

Fair concern.

I do have 2FA enabled for RubyGems.org UI, RubyGems.org API and GitHub.

**Comment by grzuy** [comment]
cc/ @frewsxcv @ktheory

**Comment by ktheory** [comment]
@lmansur: Good call. I enabled 2FA for my rubygems account.

**Comment by frewsxcv** [comment]
same here!

**Comment by lmansur** [comment]
There are 2 more owners in RubyGems, _tiegz_ and _pje_.
