### ISSUE TITLE
Anyway to make limit and time to be configurable from cache/db after deployment

### ISSUE THREAD

**Issue by warm200** [kickstarter/rack-attack#433]
```
@@limit = db.get(“limit")
@@period = db.get("period")
 throttle('requests by ip', limit: @@limit, period: @@period) do |request|
end
```
this will make people easier to change it after deploying the code in db instead change code and deploy again? but since this is in the initializer, the db call will be called once, do we have any callback to change this value?

**Comment by lmansur** [comment]
You can pass a `proc` to both limit and period. This proc will be called every time we check for a possible throttle, so you could add your database call there.

However, be wary of the performance overhead of such a call.

More info here: https://github.com/kickstarter/rack-attack#throttling

**Comment by warm200** [comment]
thanks for the prompt answer, i do have performance concern, i'll try to put the cache and see if it bothers me alot thanks!!
