### ISSUE TITLE
`RedisProxy` will still raise an error when Redis is down

### ISSUE THREAD

**Issue by avlazarov** [kickstarter/rack-attack#437]
As far as I see, the idea behind [rescuing proxy errors](https://github.com/kickstarter/rack-attack/blob/95347e35f10a145c2ab09d8a799f4702cf490c87/lib/rack/attack/store_proxy/redis_proxy.rb#L52-L56) is to not disrupt the application when there is a problem with Redis. However, if the Redis connection goes away, invocations inside `Redis#pipelined` will return an instance of `Redis::Future` before raising `Redis::CannotConnectError`, hence we'll still get an error (Redis::FutureNotReady) when [resolving its value](https://github.com/kickstarter/rack-attack/blob/95347e35f10a145c2ab09d8a799f4702cf490c87/lib/rack/attack/store_proxy/redis_proxy.rb#L43)

rack-attack version: 6.1.0
Redis gem version: 4.1.2
Rails version: 5.2.3

Can you please confirm that this is not intended?

**Comment by grzuy** [comment]
Not intended.

Thank you for reporting.

**Comment by grzuy** [comment]
From what I can tell introduced in `v6.0` by https://github.com/kickstarter/rack-attack/commit/04eeeb9a338bb81145b799565ad472e52f7b6cb5.

**Comment by grzuy** [comment]
Fixed in `v6.2.2`.
