### ISSUE TITLE
undefined method `safelist' for Rack::Attack:Class (NoMethodError) for Rails 6.0.0 api app

### ISSUE THREAD

**Issue by sledge909** [kickstarter/rack-attack#439]
Added the gem to the Gemfile and bundled.

I didn't add the `config.middleware.use Rack::Attack` line to application.rb because I'm running a Rails 6 app. 

This is my config/initializers/rack_attack.rb:

```
class Rack::Attack
  safelist('allow from valid ips') do |req|
    valid_ip_addresses.include? req.ip
  end

  def valid_ip_addresses
    [
      '62.232.106.226',
      '34.250.171.137',
      '52.51.160.179',
      '63.32.127.29',
      '34.247.249.220',
      '18.203.227.175',
      '18.203.205.196',
      '34.242.105.221',
      '52.50.60.26',
      '127.0.0.1'
    ]
  end
end

```

When I start my server I get: `undefined method 'safelist' for Rack::Attack:Class (NoMethodError)`

If I try to call any method (safelist_ip, blocklist, blocklist_ip) I get the same no method error.

I tried adding the `Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new` but I think that's only for throttling. Was worth a try.

I also tried adding the middleware line to application.rb. No dice. 

What am I missing here?

**Comment by Alexander150** [comment]
Hi.
If U find answer, write please to me!
Thanks

**Comment by fatkodima** [comment]
Use constant instead of method call:
```ruby
class Rack::Attack
  safelist('allow from valid ips') do |req|
    VALID_IP_ADDRESSES.include? req.ip
  end

  VALID_IP_ADDRESSES =
    [
      '62.232.106.226',
      '34.250.171.137',
      '52.51.160.179',
      '63.32.127.29',
      '34.247.249.220',
      '18.203.227.175',
      '18.203.205.196',
      '34.242.105.221',
      '52.50.60.26',
      '127.0.0.1'
    ]
end
```

When block is executed, this method is invisible inside it.

**Comment by grzuy** [comment]
Hi @sledge909,

I am not able to reproduce the issue by doing:
- creating new rails 6 app
- adding rack-attack 6.1
- adding your config/initializers/rack_attack.rb
- rails server

**Comment by grzuy** [comment]
Here is the test app for which I cannot reproduce the issue: https://github.com/grzuy/test_app_rack_attack_439.

**Comment by fatkodima** [comment]
@grzuy Have you tested in browser?

**Comment by grzuy** [comment]
> @grzuy Have you tested in browser?

Yes, I ran rails server for that test app, visited `http://localhost:3000` and couldn't reproduce the issue. Can you?

**Comment by fatkodima** [comment]
Yeah, I have seen slightly different error than described, but also `NoMethodError`. After proposed change everything worked correctly.

**Comment by sledge909** [comment]
Thanks for your help all. The problem was that when you copy from the clipboard on Rubygems it gives you: `gem 'rack-attack', '~> 4.4', '>= 4.4.1'` not 6.1. When I @grzuy's comment above I bundled with version 6.1 and everything works. 

I had also bundled without the versioning but of course if you have previously bundled with 4.4.1 and haven't done a bundle update it will remain at 4.4.1.
