### ISSUE TITLE
Trigger custom code on throttle/block

### ISSUE THREAD

**Issue by amitsaxena** [kickstarter/rack-attack#448]
It will be nice to be able to execute custom code when a throttle condition is met, or in fact if any of the conditions specified is met. Some kind of hook to plug in custom code. For example I want to trigger a slack notification every time an IP is throttled for exceeding rate limit. Or I want to send in details to a slack channel about every IP which was blocked along with block duration. It can be useful to maintain a kind of audit trail, or build functionality on top of it. e.g. I wanted to build functionality like:
1) Each throttle results in a slack notification
2) 3 throttles in past one hour result in a different kind on notification with a button to block user
3) An admin can click the button to add the IP to a permanent blocklist

The functionality can be easily built if I can plug in custom code into `after_throttle` and `after_blocking` callbacks/hooks.

I understand there is the `tracking` endpoint, but that isn't exactly what I was looking for. If I specify something like this:
```
track("high_request_rate", limit: 100, period: 5.minutes) do |req|
  req.ip
end
``` 
It results in a notification on 100th request and every request after that (for the 5 minute interval I guess). I also don't want to lose the throttle functionality by using track instead.

**Comment by grzuy** [comment]
> It will be nice to be able to execute custom code when a throttle condition is met, or in fact if any of the conditions specified is met. Some kind of hook to plug in custom code. For example I want to trigger a slack notification every time an IP is throttled for exceeding rate limit.

Hi @amitsaxena , you can use the notifications feature for exactly this :-)
See https://github.com/kickstarter/rack-attack#logging--instrumentation.

**Comment by amitsaxena** [comment]
Ahh! Sorry didn't notice it. Thanks for pointing that out 👍 

And thanks for the great gem! ❤️
