### ISSUE TITLE
Redis request increase upgrading 6.1.0 => 6.2.0

### ISSUE THREAD

**Issue by nadavshatz** [kickstarter/rack-attack#468]
Hi,

When upgrading the gem from `6.0.0` to `6.2.2` we've seen a huge increase in calls to redis (our cache store).

This has also increased latency.

Was this change intentional? why does this happen?

Request count from NewRelic attached:
![image](https://user-images.githubusercontent.com/1576396/71672235-15050080-2d7e-11ea-8da1-9bec8217db47.png)
_The grey line represents the release of the version with the upgraded gem_
`incrby`, `ttl` and `get` are the ones that went way up.

**Comment by nadavshatz** [comment]
Any ideas what to look into? happy to open a PR with a fix once provided with a little guidance 🙏

**Comment by grzuy** [comment]
Hi @nadavshatz ,

Thanks for the report.

A couple of questions to help in troubleshooting the issue...

Are you using rack-attack within a Rails application?
If so, which version of Rails are you using?
Was Rails version also updated when rack-attack version was updated?
Which version of the redis gem are you using?
Was the redis gem version also updated when rack-attack was updated?
What is rails `config.cache_store = ` set to in production?
Are you setting `Rack::Attack.cache.store = ` explicitly in your config?

Thanks!

**Comment by nadavshatz** [comment]
Hi @grzuy,

thanks for the reply.

- It is in a rails app.
- gem 'rails', '5.2.4.1'
- Nope, the only gem being updated to cause the change is rack-attack.
- redis (4.1.3)
- Nope, the only gem being updated to cause the change is rack-attack.
- No cache store is defined.
- Yes, added here bellow.

```rb
require 'prometheus_exporter/client'

class Rack::Attack

  if Rails.env.staging? || Rails.env.production?
    redis_url_with_auth = ENV['REDIS_URL'].sub "redis://", "rediss://user:#{ENV['REDIS_AUTH']}@"
    Rack::Attack.cache.store = ActiveSupport::Cache::RedisStore.new(redis_url_with_auth, { expires_in: 90.minutes })
  end

  client = PrometheusExporter::Client.default
  gauge = client.register(:gauge , "sauron.rackattack.req_per_ip", "blocked by ip")

  limit =  Rails.configuration.ratelimit["requests"] || 0
  period =  Rails.configuration.ratelimit["period"] || 1
  internal_limit =  Rails.configuration.ratelimit["internal_requests"] || limit
  internal_period =  Rails.configuration.ratelimit["internal_period"] || period
  internal_path = "/internal"

  # Excludes internal routes
  Rack::Attack.track("req_per_ip_external", limit: limit, period: period.seconds) do |req|
    distinguisher = "#{req.ip}, #{req.request_method}, #{req.path}"
    distinguisher unless req.path.start_with?(internal_path)
  end

  # Only internal routes
  Rack::Attack.track("req_per_ip_internal", limit: internal_limit, period: internal_period.seconds) do |req|
    distinguisher = "#{req.ip}, #{req.request_method}, #{req.path}"
    distinguisher if req.path.start_with?(internal_path)
  end

  # Track it using ActiveSupport::Notification
  ActiveSupport::Notifications.subscribe(/rack_attack/) do |name, start, finish, request_id, payload|
    req = payload[:request]
    attack = req.env['rack.attack.matched']
    Rails.logger.warn(event: "rack_attack_triggered", attack_type: attack, ip: req.ip, method: req.request_method, path: req.path)
    if Rails.env.production? || Rails.env.staging?
      gauge.observe(1)
    end
  end
end
```

Any help would be greatly appreciated!

**Comment by grzuy** [comment]
Thank you.

From looking at your config I infer you're using `redis-activesupport`.
Which version of that gem do you have in your lockfile?

**Comment by nadavshatz** [comment]
@grzuy 
 
`redis-activesupport (5.2.0)`

**Comment by grzuy** [comment]
Thank you.

Wasn't able to see any increment in redis operations within this test app I created from scratch: https://github.com/grzuy/test_app_rack_attack_468/commit/78215ae3a97cc6a3a04fa2fa9cfd3c407ed5e61b.

Feel free to fork and try reproducing the issue by adding more stuff to the test app...

**Comment by nadavshatz** [comment]
I'm afraid building a test app and just running won't show the change.

When checking this on our staging site we didn't see the issue either, only when it was on production - which makes me think it is reliant on real traffic.

The specific service we use this for get lots of traffic.
This also made it quite difficult for us to find the culprit since we had to /test/ on production.

All of this makes me think there was a change in the code that would cause it to make more requests (or some that didn't happen before) to the cache per request.
Only other thing i can think of is that a change actually fixed a bug and before that it didn't use the cache at all, tho i find this a lot less likely.

wdyt?

**Comment by grzuy** [comment]
> I'm afraid building a test app and just running won't show the change.
> 
> When checking this on our staging site we didn't see the issue either, only when it was on production - which makes me think it is reliant on real traffic.

Oh, I see.

Well, that may be helpful for debugging, the fact that you know it's something present in production and not in staging. You can explore testing locally and start setting development configs to mirror production, like caching and others...

In order to flag this as a bug in rack-attack and try fixing it we would need to confirm it's there (and not somewhere else), and reproduce it.

So, if the bug is in rack-attack, and considering the small footprint of rack-attack, I can't think of any reason why we wouldn't be able to reproduce it with a test app. It's a matter of putting enough stuff in that test app to make it happen.

> 
> The specific service we use this for get lots of traffic.
> This also made it quite difficult for us to find the culprit since we had to _test_ on production.
> 
> All of this makes me think there was a change in the code that would cause it to make more requests (or some that didn't happen before) to the cache per request.
> Only other thing i can think of is that a change actually fixed a bug and before that it didn't use the cache at all, tho i find this a lot less likely.
> 
> wdyt?

**Comment by nadavshatz** [comment]
Our staging environment matches our production env settings. this is intentional.
The only thing really different is the load the system receives since we don't shadow traffic.

Doing so locally won't work unless we try to stress test it. that might work.

the reason i'm confident that the issue lies with rack-attack is that, that is literally the only code change in the entire deployment and the change in NewRelic is seen immediately. 

happy yo hear further thoughts.

**Comment by driv3r** [comment]
@nadavshatz to narrow it down, maybe you could downgrade rack attack to 6.1 to see if it's high as well? Doing version by version would narrow down the possible issues.

**Comment by nadavshatz** [comment]
@driv3r great idea - just tested and `6.1` works fine.
I assume the issue is wit 6.2.x then.

Maybe the change for redis that is mentioned in the change log?
Could this PR be the culprit https://github.com/kickstarter/rack-attack/pull/421 ?

**Comment by grzuy** [comment]
Thank you @driv3r and @nadavshatz for this extra information.

I am updating the issue title to reflect that.

**Comment by grzuy** [comment]
> @driv3r great idea - just tested and `6.1` works fine.
> I assume the issue is wit 6.2.x then.
> 
> Maybe the change for redis that is mentioned in the change log?
> Could this PR be the culprit #421 ?

In theory it should be #421, because that's only changing `RedisCacheStoreProxy` and you are using `RedisStoreProxy`.

A possibility is https://github.com/kickstarter/rack-attack/pull/445, which change `RedisProxy`, which `RedisStoreProxy` inherits from.

That change is part of `v6.2.2` only.
Can you confirm that `6.2.1` works fine for you?

**Comment by nadavshatz** [comment]
@grzuy I tested 6.2.1 and got the issue!
![image](https://user-images.githubusercontent.com/1576396/73187807-a459c580-412a-11ea-846b-1867f2cebea6.png)

Updating the issue title accordingly 👍 

Any other ideas?

**Comment by grzuy** [comment]
> > @driv3r great idea - just tested and `6.1` works fine.
> > I assume the issue is wit 6.2.x then.
> > Maybe the change for redis that is mentioned in the change log?
> > Could this PR be the culprit #421 ?
> 
> In theory it should NOT be #421, because that's only changing `RedisCacheStoreProxy` and you are using `RedisStoreProxy`.

Correcting myself. You are using `ActiveSupportRedisStoreProxy`, not `RedisStoryProxy`.

That means you shouldn't, theoretically, be affected by #421 nor #455.
My bad.

> 
> A possibility is #445, which changes `RedisProxy`, which `RedisStoreProxy` inherits from.
> 
> That change is part of `v6.2.2` only.
> Can you please confirm that `6.2.1` works fine for you?

**Comment by grzuy** [comment]
> @grzuy I tested 6.2.1 and got the issue!
> ![image](https://user-images.githubusercontent.com/1576396/73187807-a459c580-412a-11ea-846b-1867f2cebea6.png)
> 
> Updating the issue title accordingly +1

Gotcha.
Thank your for that!

> 
> Any other ideas?

There's nothing obvious to me from comparing [`v6.1.0...v6.2.1`](https://github.com/kickstarter/rack-attack/compare/v6.1.0...v6.2.1?w=1).

If you want you can test with `v6.2.0` to narrow it down even further.
In any case, if we think this is a rack-attack issue that's causing more redis operations, we will need to reproduce the issue somehow...

**Comment by nadavshatz** [comment]
I'll try it tomorrow to narrow it down further.

And I'm sure it's a rack-attack issue see the CPM rise from ~250 to >6K immediately after the deploy. it also drops immediately when i revert the change.
The only difference is this gem version.

I'm not saying it can't be an issue with our setup - but even if it is, what would it be that only these specific versions cause it?

**Comment by grzuy** [comment]
> I'll try it tomorrow to narrow it down further.

Cool, thank you! :-)

> 
> And I'm sure it's a rack-attack issue see the CPM rise from ~250 to >6K immediately after the deploy. it also drops immediately when i revert the change.
> The only difference is this gem version.
> 
> I'm not saying it can't be an issue with our setup - but even if it is, what would it be that only these specific versions cause it?

If you're experiencing that spike by only updating rack-attack, definitely rack-attack is contributing to the problem in some way.

The thing is that I was not able to reproduce the increase in redis operations with a clean rails test app in https://github.com/grzuy/test_app_rack_attack_468.

This means, it's reproducible in your production application and not on my rails test app.

We need to find out what else can be added to the rails test app to make the issue manifest. I don't see any other option than that except from guessing.

**Comment by nadavshatz** [comment]
@grzuy as explained earlier we don't see it on our staging sites (low traffic) either. which makes me think it requires large traffic to reproduce.

I've tested 6.2 and it's broken as well - so now we know for sure it's something 6.1 <-> 6.2
![image](https://user-images.githubusercontent.com/1576396/73263439-3d471a00-41d9-11ea-8054-ed8226b97567.png)

Updating the issue title

**Comment by grzuy** [comment]
OK.

Thank you for testing once again!

**Comment by nadavshatz** [comment]
the actual calls that increase are `incrby` `ttl` and `get` if that helps.

**Comment by grzuy** [comment]
Gotcha. Thanks.

If you were able to narrow down which is the specific line (or lines) inside rack-attack, by looking at new relic or logs, that generate those spikes, it would be very helpful.

**Comment by nadavshatz** [comment]
We don't have this level of detail in new relic or logs i'm afraid.
It looks like it's happening from the routes it's protecting...

**Comment by driv3r** [comment]
@nadavshatz what's the limit/period config?

**Comment by nadavshatz** [comment]
```yml
  requests: 100
  period: 60
  internal_requests: 1000
  internal_period: 30
```

**Comment by nadavshatz** [comment]
> @nadavshatz what's the limit/period config?

```yml
  requests: 100
  period: 60
  internal_requests: 1000
  internal_period: 30
```

**Comment by driv3r** [comment]
I couldn't see any obvious issues, my current guess would be that it can be related to the position of middleware in the stack which was added in this version. 

@nadavshatz Could you try running `RAILS_ENV=production bundle exec rake middleware` against 6.1 and 6.2 versions of rack attack? check if positions are different. 

Also check if there's anything else using Redis, i.e. Prometheus Exporter middleware patches `Redis::Client`

**Comment by nadavshatz** [comment]
@driv3r indeed 6.2 adds `Rack::Attack` as a middleware, which isn't included at all at 6.1

Nothing else is different since we don't change anything in the code except the gem's version.

Let me know if I can assist further.

**Comment by driv3r** [comment]
@nadavshatz if in 6.1 you can't see the middleware, then it means you haven't really used it, no? This would explain that with 6.2 and auto adding middleware you have actually started using the rack attack, which resulted in bigger usage of Redis, wdys?

**Comment by nadavshatz** [comment]
I added here the settings we’re using. Was there anything more we needed to do in 6.1?

Nadav Shatz
Tailor Brands | CTO

**Comment by nadavshatz** [comment]
Found the missing config 🤦‍♂ 

Sorry for the noise.
Thanks for the help everyone! it really seems like it wasn't actually runing.
@driv3r thanks for the idea!

Closing this 🙏

**Comment by grzuy** [comment]
@nadavshatz No worries :-) Thanks for the update.

@driv3r Thank you very much for your help!

In a way this reinforces #429 being a good idea. The initial motivation for that was to simplify installation, but I now wonder if there are more rails app out there with rack-attack disabled (beacuse of not adding middleware manually) without even knowing. Hopefully from `v6.2` onwards, auto middleware insertion make that no longer a possibility :-)
