### ISSUE TITLE
Throttler not working normally after upgrade from 5.4.2 to 6.2.2

### ISSUE THREAD

**Issue by Altareq** [kickstarter/rack-attack#470]
after upgrading the gem to latest, started seeing unexpected behaviour on throttlers, rolling back to 5.4.2 fixes the issue but that version is far behind. Could not find time to look deep on where it happens. Redis is used locally and production.

at 5.4.2 the gem throttles properly, example send 200 req/s and set limit at 1 req/s, only one req/s gets allowed, same test on 6.x.x allows sometimes 3 req/s. Setting the limit to 50 req/s, and sending 500 req/s on > 6  releases, allows sometimes 120 req/s which can bring bad expectations.

**Comment by grzuy** [comment]
Hi @Altareq ,

Thank you for reporting.

In order to help troubleshoot, can you please let us know...

- Are you using rack-attack within a Rails application?
- Which Rails version are you using?
- What is Rails `config.cache_store = ` set to on production?
- Which redis gem version are you using?
- Are you explicitly setting `Rack::Attack.cache.store = ` in your config?
- Was the rack-attack update part of a larger update, including more gems? In particular rails or redis gem?

Thanks in advance.

**Comment by Altareq** [comment]
Hello @grzuy ,

- Yes it is a Rails application.
- Rails version `6.0.2.1`.
- ```redis_store``` Redis running local as a single master instance, Redis is running in cluster mode in production with a master and several replicas, cluster managed by sentinels.  (problem happens in both environments).
- redis gem version `4.1.3`.
- No `Rack::Attack.cache.store` is not set manually.
- Yes it was an update with few other gems, including rails to `6.0.2.1` redis to `4.1.3` redis-store to `1.8.1`.

After several hours looking into why throttling stopped working properly, we did not find anything suspicious, so we locked the rack-attack gem back at `5.4.2` and throttling worked again without problems. All other gems were not changed.

Let us see if you can reproduce, otherwise let me know if you need any other details. 

Thanks for your help.

**Comment by grzuy** [comment]
Hi @Altareq,

Would it be possible for you to test with incrementing rack-attack version to `v6.0` and then to `v6.1`? So that we can narrow down the problem to a more specific version?

Thanks in advance!

**Comment by grzuy** [comment]
Closing for lack of information to further triage the problem.

@Altareq Happy to re-open if we get more information.

Thanks for reporting.

**Comment by aksh-gupta** [comment]
@Altareq Did you find the issue or you are still using `5.4.2`?
