### ISSUE TITLE
Throttle limit access on a per user basis in an API only app

### ISSUE THREAD

**Issue by mithesh109** [kickstarter/rack-attack#471]
Hello,

I'd like to know if throttling can be configured on a per user basis in a Rails 5 API application.
I have a token generated for each user and throttling is done based on this token.

Is it possible to store these token values or user details in a yml file and then Rack Attack uses this yml file to set the throttle limit and period on a per user basis.

If this approach is not feasible, what would be a better way to go through about this issue.

I do not want to set the throttle values on a database level for each user.

**Comment by grzuy** [comment]
> Hello,
> 
> I'd like to know if throttling can be configured on a per user basis in a Rails 5 API application.
> I have a token generated for each user and throttling is done based on this token.

Hi @mithesh109 ,

If each user has a different token, and you're throttling based on token, you're already limiting access on a per user basis, aren't you?

> 
> Is it possible to store these token values or user details in a yml file and then Rack Attack uses this yml file to set the throttle limit and period on a per user basis.
> 
> If this approach is not feasible, what would be a better way to go through about this issue.
> 
> I do not want to set the throttle values on a database level for each user.

**Comment by mithesh109** [comment]
> 
> Hi @mithesh109 ,
> 
> If each user has a different token, and you're throttling based on token, you're already limiting access on a per user basis, aren't you?
> 

Hi @grzuy ,

`` 
throttle('info', limit: 50, period: 5.hours) do |req|
    if req.path == "info" && req.post?
      req.env["HTTP_USERTOKEN"]
    end
  end
``

This is my throttling code in rack_attack initializer file. Currently, all users have a set request limit of 50 requests for 5 hours.

My issue is that I want to set different throttling limits for each user. Let's say, UserA can send 100 requests in 5 hours, UserB can send 50 requests in 5 hours, UserC can send 50 requests every hour. How do I achieve this without storing these throttle values in the database? Is it possible to store the throttle values for users in a yml file and the Rack Attack references that file to check the throttle limit.

**Comment by grzuy** [comment]
> > Hi @mithesh109 ,
> > If each user has a different token, and you're throttling based on token, you're already limiting access on a per user basis, aren't you?
> 
> Hi @grzuy ,
> 
> ` throttle('info', limit: 50, period: 5.hours) do |req| if req.path == "info" && req.post? req.env["HTTP_USERTOKEN"] end end`
> 
> This is my throttling code in rack_attack initializer file. Currently, all users have a set request limit of 50 requests for 5 hours.
> 
> My issue is that I want to set different throttling limits for each user. Let's say, UserA can send 100 requests in 5 hours, UserB can send 50 requests in 5 hours, UserC can send 50 requests every hour. 

Gotcha.

> How do I achieve this without storing these throttle values in the database? Is it possible to store the throttle values for users in a yml file and the Rack Attack references that file to check the throttle limit.

You can have different period and limit values calculated per request, and not fixed. See the example with the procs in https://github.com/kickstarter/rack-attack/#throttling.

**Comment by mithesh109** [comment]
Hi @grzuy ,

I did go through procs throttling, but that wouldn't help in my cause.
`limit_proc = proc { |req| req.env["REMOTE_USER"] == "admin" ? 100 : 1 }`  
Here we can only check for a single user, for multiple users I will have to create multiple procs.

I would need something like 
`limit_proc = proc { |req| req.env["HTTP_USERTOKEN"] is present in yml file ? Load limit from yml for user : default[:limit] }  period_proc = proc { |req| req.env["HTTP_USERTOKEN"] is present in yml file ? Load limit from yml for user : default[:period] }`

And then my yml file would contain
UserA:
  limit: 50
  period: 5.hours

UserB:
  limit: 100
  period: 2.hours

UserC:
  limit: 10
  period: 20.minutes

default:
  limit: 5
  period: 12.hours

**Comment by grzuy** [comment]
Yes.

rack-attack gives you the flexibility of having limit and periods depend on each request. It's up to you to do whatever you need, either simple or complex calculation, to respond with the necessary limit and period values.

If you need to read/write files you can, if you need to read/write that info to somewhere else you also can. You can do whatever you need to in that ruby block. All rack-attack needs is that you respond with the limit/period values, that's all.
