### ISSUE TITLE
Getting (EACCES (Permission denied)) when using file_store as the cache when deploying on an azure app service(WebApp)

### ISSUE THREAD

**Issue by mrinalsymc** [kickstarter/rack-attack#472]
Hi,

I am using rack-attack with the `file_store` as the cache for an app i have deployed as a azure WebApp(app service). the rails version is 2.3.8 and rackattack gem version is 5.0.1.

I am aware that the azure app service can scale up to multiple servers, and if that does then `file_store` might not be the correct option. But currently I am not expecting my service to scale up, cause only my team is using it. 

So whenever i refresh my page i get a 500 internal server error and when i look at the logs
```
Errno::EACCES (Permission denied @ rb_file_s_rename - (/home/site/wwwroot/tmp/cache/rack%3A%3Aattack%3A2632711%3Asign_in%2Fip%3A155.64.38.124%3A3229920200121-191-gbb78k, /home/site/wwwroot/tmp/cache/10D/561/rack%3A%3Aattack%3A2632711%3Asign_in%2Fip%3A155.64.38.124%3A32299)):
  lib/compressed_requests.rb:24:in `call'
```
I checked the user and the group for the given folders above and they are `nobody/nogroup`. So it is not the case of the process not having access to the folder else it would have failed everytime and when it succeeds I do see the `rack-attack*` file being moved to the correct folder.

**Comment by grzuy** [comment]
> Hi,

Hi @mrinalsymc !

> 
> I am using rack-attack with the `file_store` as the cache for an app i have deployed as a azure WebApp(app service). the rails version is 2.3.8 and rackattack gem version is 5.0.1.

Can you confirm you're using Rails version `v2.3.8` or you meant Ruby version `v2.3.8`?

> 
> I am aware that the azure app service can scale up to multiple servers, and if that does then `file_store` might not be the correct option. But currently I am not expecting my service to scale up, cause only my team is using it.
> 
> So whenever i refresh my page i get a 500 internal server error and when i look at the logs
> 
> ```
> Errno::EACCES (Permission denied @ rb_file_s_rename - (/home/site/wwwroot/tmp/cache/rack%3A%3Aattack%3A2632711%3Asign_in%2Fip%3A155.64.38.124%3A3229920200121-191-gbb78k, /home/site/wwwroot/tmp/cache/10D/561/rack%3A%3Aattack%3A2632711%3Asign_in%2Fip%3A155.64.38.124%3A32299)):
>   lib/compressed_requests.rb:24:in `call'
> ```

I don't see anything there mentioning rack-attack.

Can you please provide if possible, complete error backtrace?

> 
> I checked the user and the group for the given folders above and they are `nobody/nogroup`. So it is not the case of the process not having access to the folder else it would have failed everytime and when it succeeds I do see the `rack-attack*` file being moved to the correct folder.

Thank you!

**Comment by mrinalsymc** [comment]
oops sorry i meant ruby version 2.3.8 and rails version v4.1.16. The only logs that i have are
```
I, [2020-01-24T17:45:04.043379 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b] Started GET "/admins/sign_in" for 155.64.38.89:53898 at 2020-01-24 17:45:04 +0000
I, [2020-01-24T17:45:04.133407 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b] Processing by Devise::SessionsController#new as HTML
I, [2020-01-24T17:45:04.160264 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered authenticable_users/shared/_devise_alerts.html.erb (0.2ms)
I, [2020-01-24T17:45:04.161140 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered authenticable_users/shared/_form_validation.html.erb (0.1ms)
I, [2020-01-24T17:45:04.161334 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered devise/sessions/new.html.erb within layouts/devise (19.3ms)
I, [2020-01-24T17:45:04.161822 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered layouts/_common_head.html.erb (0.3ms)
I, [2020-01-24T17:45:04.162436 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered layouts/_placeholder_support.html.erb (0.1ms)
I, [2020-01-24T17:45:04.162930 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b]   Rendered authenticable_users/shared/_links.html.erb (0.1ms)
I, [2020-01-24T17:45:04.163433 #192]  INFO -- : [182531e3-88e1-4693-acb2-61cd8ef8173b] Completed 200 OK in 30ms (Views: 21.7ms | ActiveRecord: 0.0ms)
I, [2020-01-24T17:45:07.417801 #192]  INFO -- : [2af5cc31-8121-4e9c-94e9-917861894318] Started POST "/admins/sign_in" for 155.64.38.89:53898 at 2020-01-24 17:45:07 +0000
I, [2020-01-24T17:45:07.621897 #192]  INFO -- : [2af5cc31-8121-4e9c-94e9-917861894318] Error while sending Airbrake.
F, [2020-01-24T17:45:08.138878 #192] FATAL -- : [2af5cc31-8121-4e9c-94e9-917861894318] 
Errno::EACCES (Permission denied @ rb_file_s_rename - (/home/site/wwwroot/tmp/cache/rack%3A%3Aattack%3A2633146%3Asign_in%2Fip%3A155.64.38.89%3A5389820200124-192-1wnexj6, /home/site/wwwroot/tmp/cache/0F2/5E1/rack%3A%3Aattack%3A2633146%3Asign_in%2Fip%3A155.64.38.89%3A53898)):
  lib/compressed_requests.rb:24:in `call'
```
I had narrowed it down to rack-attack cause it was in file name moving `rack::attack:2633146:sign_in/ip:155.64.38.89:5389820200124-192-1wnexj6` which was throwing an error.

One more thing, the error stopped happening as soon as i move to the inprocess memory

**Comment by grzuy** [comment]
Hi @mrinalsymc ,

I still don't see anything that points to an issue in rack-attack.
Still feels like something specific to permissions in your deployment environment. There's nothing in rack-attack's source code doing file renaming.

If possible, I recommend updating rails and rack-attack version, those you're using are 4-5 years old.

Sorry to say there's not a lot we can do to help with the information you provided so far.
