### ISSUE TITLE
ability to block by domain

### ISSUE THREAD

**Issue by jtoy** [kickstarter/rack-attack#475]
I have a site that has multiple CNAMEs pointed at it.  I was trying to filter by domain, but rack-attack doesn't seem to support it. I would like the ability to filter, block, and other functions at the domain level.Is it possible with current code? it seems like it needs large code modifications to handle this.

**Comment by grzuy** [comment]
Hi @jtoy ,

rack-attack yields the `Rack::Request` object in the ruby block for you to do whatever you need with that, like in...

```ruby
Rack::Attack.throttle("requests by ip", limit: 5, period: 2) do |request|
  # your code here with access to the `Rack::Request`
end
```
