### ISSUE TITLE
How to view what has been blocked on a production server?

### ISSUE THREAD

**Issue by gregblass** [kickstarter/rack-attack#476]
Hey there!

Apologies for the newbie question. I'm trying to view what has been blocked on a production server. I have no experience whatsoever with caching, so I'm not sure how to view the default production cache to check this. We have not configured memcached or redis.

How would I go about accessing that information?

Thank you!

**Comment by gregblass** [comment]
I see that logging is the preferred way to do this.

**Comment by grzuy** [comment]
Hi @gregblass,

> We have not configured memcached or redis.

Are you using `rack-attack` within a Rails application?
What is `Rails.configuration.cache_store` set to in `production`?
Are you setting `Rack::Attack.cache.store` explicitly in your rack-attack config or leaving it to the default value?

Thanks.
