### ISSUE TITLE
is it possible to add certain ip to banned list from rails controller?

### ISSUE THREAD

**Issue by saiqulhaq** [kickstarter/rack-attack#479]
Let say there is error `ArgumentError: invalid %-encoding (*%7PRZNVY%7P*)`
I would like to ban this user
is it possible?

**Comment by grzuy** [comment]
Hi,

`Rack::Attack` is a middleware, so it's scope its the middleware stack and not a Rails controller.

That's all I can say.
For more details maybe you want to rephrase/expand your question with code examples maybe.

Thanks.
