### ISSUE TITLE
X-RateLimit headers

### ISSUE THREAD

**Issue by gvc** [kickstarter/rack-attack#50]
I'm building an API with throttling and the API has well educated clients, that can respect the X-RateLimit headers. I haven't found a way to do this in the rack-attack gem. Is there an interest in this feature for throttling? I can develop, but was just wondering if it's desirable to the gem.

Many APIs are using this already:
http://developer.github.com/v3/#rate-limiting
http://developer.vimeo.com/guidelines/rate-limiting
https://dev.twitter.com/docs/rate-limiting/1.1

Looking forward for your feedback.

**Comment by dapicester** [comment]
@gvc have a look at this: https://github.com/jbyck/rack-attack-rate-limit
